# -*- coding: utf-8 -*-
"""Q-PIPE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CT5i9Tx0rM39AkvsVtiuAK58t39mGUqM
"""

!pip install pennylane --quiet

import pennylane as qml
import numpy as np
from numpy.linalg import norm
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
from sklearn.metrics import mean_absolute_error
import itertools

"""# Proof of concept: Detección de bordes (corregido usando rango $-\pi$ a $\pi$ + corrección de spectral leakage)

## Desplazamiento horizontal (MAE = 0 + spectral leakage)
"""

### CODIFICACIÓN Y DIFERENCIA DE FASES (desplazamiento horizontal) ###
def apply_dual_phases_with_gray_code(flat_phases_1, flat_phases_2, img_wires, est_wire, power):
    n = len(img_wires)
    total_states = 2**n
    gray_seq = [i ^ (i >> 1) for i in range(total_states)]

    for w in img_wires:
        qml.PauliX(wires=w)

    target_wire = img_wires[-1]
    control_wires = [est_wire] + list(img_wires[:-1])

    for step in range(total_states):
        curr_gray = gray_seq[step]
        pixel_idx = curr_gray

        if pixel_idx < len(flat_phases_1):
            phi1 = flat_phases_1[pixel_idx]
            phi2 = flat_phases_2[pixel_idx]

            if abs(phi1) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi1 * power, wires=target_wire)
            if abs(phi2) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi2 * power, wires=target_wire)

        if step < total_states - 1:
            next_gray = gray_seq[step + 1]
            diff = curr_gray ^ next_gray
            bit_changed_from_right = int(np.log2(diff))
            wire_to_flip = img_wires[n - 1 - bit_changed_from_right]
            qml.PauliX(wires=wire_to_flip)

    last_gray_bin = format(gray_seq[-1], f'0{n}b')
    for i, bit in enumerate(last_gray_bin):
        if bit == '0':
            qml.PauliX(wires=img_wires[i])

### Parametros del circuito cuántico ###
n_pixels = 64
n_image_wires = 6
n_estimation_wires = 8
total_wires = n_estimation_wires + n_image_wires

dev = qml.device('default.qubit', wires=total_wires)

@qml.qnode(dev)
def edge_detection_circuit(flat_p1, flat_p2):
    est_wires = list(range(n_estimation_wires))
    tgt_wires = list(range(n_estimation_wires, total_wires))

    for w in est_wires + tgt_wires:
        qml.Hadamard(wires=w)

    for i, est_wire in enumerate(reversed(est_wires)):
        power = 2**i
        apply_dual_phases_with_gray_code(flat_p1, flat_p2, tgt_wires, est_wire, power)

    qml.adjoint(qml.QFT)(wires=est_wires)
    return qml.probs(wires=est_wires + tgt_wires)

## Cargar dataset "digits"
digits = load_digits()
images_to_test = digits.images[:5]
targets = digits.target[:5]

fig, axes = plt.subplots(5, 4, figsize=(14, 16))

# Umbral (puede modificarse) para 8 qubits de estimación.
prob_threshold = 0.001 # Base para resolucion 8x8.

for idx, raw_img in enumerate(images_to_test):
    raw_img = (raw_img / 16.0) * 255.0

    shifted_img = np.roll(raw_img, shift=1, axis=1)
    shifted_img[:, 0] = 0

    classical_gradient = np.abs(raw_img - shifted_img)

    ## CORRECCIÓN: Multiplicamos por pi, no por 2*pi ##
    phases_base = (raw_img.flatten() / 255.0) * np.pi
    phases_shifted_neg = (-shifted_img.flatten() / 255.0) * np.pi

    print(f"Calculando QPE para dígito {targets[idx]} ({idx+1}/5)...")
    probs = edge_detection_circuit(phases_base, phases_shifted_neg)

    weighted_mag_sum = np.zeros_like(raw_img, dtype=float)
    prob_sum = np.zeros_like(raw_img, dtype=float)

    for k, p in enumerate(probs):
        if p > prob_threshold:
            bin_k = format(k, f'0{total_wires}b')
            est_int = int(bin_k[:n_estimation_wires], 2)
            pixel_idx = int(bin_k[n_estimation_wires:], 2)

            if pixel_idx < n_pixels:
                row, col = np.unravel_index(pixel_idx, raw_img.shape)
                raw_val = (est_int / (2**n_estimation_wires)) * 255.0

                # Nueva decodificación: Como mapeamos a la mitad de la fase (pi),
                # la magnitud real es el doble de la distancia extraída.
                edge_magnitude = 2.0 * min(raw_val, 255.0 - raw_val)

                weighted_mag_sum[row, col] += p * edge_magnitude
                prob_sum[row, col] += p

    safe_prob_sum = np.where(prob_sum == 0, 1.0, prob_sum)
    quantum_edge_img = weighted_mag_sum / safe_prob_sum

    mae_score = mean_absolute_error(classical_gradient.flatten(), quantum_edge_img.flatten())
    print(f"  -> MAE Horizontal: {mae_score:.4f}")

    # Visualización
    axes[idx, 0].imshow(raw_img, cmap='gray', vmin=0, vmax=255)
    axes[idx, 0].set_title(f"Original: {targets[idx]}")
    axes[idx, 0].axis('off')

    axes[idx, 1].imshow(shifted_img, cmap='gray', vmin=0, vmax=255)
    axes[idx, 1].set_title("Displaced")
    axes[idx, 1].axis('off')

    axes[idx, 2].imshow(classical_gradient, cmap='gray', vmin=0, vmax=255)
    axes[idx, 2].set_title("Classical gradient")
    axes[idx, 2].axis('off')

    axes[idx, 3].imshow(np.clip(quantum_edge_img, 0, 255), cmap='gray', vmin=0, vmax=255)
    axes[idx, 3].set_title(f"Q-PIPE gradient \nMAE: {mae_score:.2f}")
    axes[idx, 3].axis('off')

plt.tight_layout()
plt.savefig("edge_detection_circuit_mnist_horizontal.png", dpi=600)
plt.savefig("edge_detection_circuit_mnist_horizontal.eps")
plt.show()
print("Procesamiento cuántico corregido finalizado.")

"""## Desplazamiento vertical (corrección de mapeo + spectral leakage)"""

### CODIFICACIÓN Y DIFERENCIA DE FASES (desplazamiento vertical) ###
def apply_dual_phases_with_gray_code(flat_phases_1, flat_phases_2, img_wires, est_wire, power):
    n = len(img_wires)
    total_states = 2**n
    gray_seq = [i ^ (i >> 1) for i in range(total_states)]

    for w in img_wires:
        qml.PauliX(wires=w)

    target_wire = img_wires[-1]
    control_wires = [est_wire] + list(img_wires[:-1])

    for step in range(total_states):
        curr_gray = gray_seq[step]
        pixel_idx = curr_gray

        if pixel_idx < len(flat_phases_1):
            phi1 = flat_phases_1[pixel_idx]
            phi2 = flat_phases_2[pixel_idx]

            if abs(phi1) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi1 * power, wires=target_wire)
            if abs(phi2) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi2 * power, wires=target_wire)

        if step < total_states - 1:
            next_gray = gray_seq[step + 1]
            diff = curr_gray ^ next_gray
            bit_changed_from_right = int(np.log2(diff))
            wire_to_flip = img_wires[n - 1 - bit_changed_from_right]
            qml.PauliX(wires=wire_to_flip)

    last_gray_bin = format(gray_seq[-1], f'0{n}b')
    for i, bit in enumerate(last_gray_bin):
        if bit == '0':
            qml.PauliX(wires=img_wires[i])

## Parametros del circuito cuántico
n_pixels = 64
n_image_wires = 6
n_estimation_wires = 8
total_wires = n_estimation_wires + n_image_wires

dev = qml.device('default.qubit', wires=total_wires)

@qml.qnode(dev)
def edge_detection_circuit(flat_p1, flat_p2):
    est_wires = list(range(n_estimation_wires))
    tgt_wires = list(range(n_estimation_wires, total_wires))

    for w in est_wires + tgt_wires:
        qml.Hadamard(wires=w)

    for i, est_wire in enumerate(reversed(est_wires)):
        power = 2**i
        apply_dual_phases_with_gray_code(flat_p1, flat_p2, tgt_wires, est_wire, power)

    qml.adjoint(qml.QFT)(wires=est_wires)
    return qml.probs(wires=est_wires + tgt_wires)

## Carga dataset
digits = load_digits()
images_to_test = digits.images[:5]
targets = digits.target[:5]

fig, axes = plt.subplots(5, 4, figsize=(14, 16))

prob_threshold = 0.001

for idx, raw_img in enumerate(images_to_test):
    # Normalización
    raw_img = (raw_img / 16.0) * 255.0

    # Preprocesamiento: Desp. VERTICAL (axis=0)
    shifted_img_y = np.roll(raw_img, shift=1, axis=0)
    shifted_img_y[0, :] = 0  # Limpiar la primera fila (bordes envueltos)

    classical_gradient_y = np.abs(raw_img - shifted_img_y)

    # Escalamiento de media fase.
    phases_base = (raw_img.flatten() / 255.0) * np.pi
    phases_shifted_neg_y = (-shifted_img_y.flatten() / 255.0) * np.pi

    print(f"Calculando QPE Vertical para dígito {targets[idx]} ({idx+1}/5)...")
    probs = edge_detection_circuit(phases_base, phases_shifted_neg_y)

    weighted_mag_sum = np.zeros_like(raw_img, dtype=float)
    prob_sum = np.zeros_like(raw_img, dtype=float)

    for k, p in enumerate(probs):
        if p > prob_threshold:
            bin_k = format(k, f'0{total_wires}b')
            est_int = int(bin_k[:n_estimation_wires], 2)
            pixel_idx = int(bin_k[n_estimation_wires:], 2)

            if pixel_idx < n_pixels:
                row, col = np.unravel_index(pixel_idx, raw_img.shape)
                raw_val = (est_int / (2**n_estimation_wires)) * 255.0

                # Decodificación y ajuste de escala x2
                edge_magnitude = 2.0 * min(raw_val, 255.0 - raw_val)

                weighted_mag_sum[row, col] += p * edge_magnitude
                prob_sum[row, col] += p

    safe_prob_sum = np.where(prob_sum == 0, 1.0, prob_sum)
    quantum_edge_img_y = weighted_mag_sum / safe_prob_sum

    # Métrica
    mae_score = mean_absolute_error(classical_gradient_y.flatten(), quantum_edge_img_y.flatten())
    print(f"  -> MAE Vertical: {mae_score:.4f}")

    # Visualización
    axes[idx, 0].imshow(raw_img, cmap='gray', vmin=0, vmax=255)
    axes[idx, 0].set_title(f"Original: {targets[idx]}")
    axes[idx, 0].axis('off')

    axes[idx, 1].imshow(shifted_img_y, cmap='gray', vmin=0, vmax=255)
    axes[idx, 1].set_title("Displaced")
    axes[idx, 1].axis('off')

    axes[idx, 2].imshow(classical_gradient_y, cmap='gray', vmin=0, vmax=255)
    axes[idx, 2].set_title("Classical gradient")
    axes[idx, 2].axis('off')

    axes[idx, 3].imshow(np.clip(quantum_edge_img_y, 0, 255), cmap='gray', vmin=0, vmax=255)
    axes[idx, 3].set_title(f"Q-PIPE gradient \nMAE: {mae_score:.2f}")
    axes[idx, 3].axis('off')

plt.tight_layout()
plt.savefig("edge_detection_circuit_mnist_vertical.png", dpi=600)
plt.savefig("edge_detection_circuit_mnist_vertical.eps")
plt.show()
print("Procesamiento cuántico vertical finalizado.")

"""## Desplazamiento combinado (metrica de Sobel)"""

### DESPLAZAMIENTO COMBINADO (SOBEL + mapeo corregido + corrección spectral leakage)
def apply_dual_phases_with_gray_code(flat_phases_1, flat_phases_2, img_wires, est_wire, power):
    n = len(img_wires)
    total_states = 2**n
    gray_seq = [i ^ (i >> 1) for i in range(total_states)]

    for w in img_wires:
        qml.PauliX(wires=w)

    target_wire = img_wires[-1]
    control_wires = [est_wire] + list(img_wires[:-1])

    for step in range(total_states):
        curr_gray = gray_seq[step]
        pixel_idx = curr_gray

        if pixel_idx < len(flat_phases_1):
            phi1 = flat_phases_1[pixel_idx]
            phi2 = flat_phases_2[pixel_idx]

            if abs(phi1) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi1 * power, wires=target_wire)
            if abs(phi2) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi2 * power, wires=target_wire)

        if step < total_states - 1:
            next_gray = gray_seq[step + 1]
            diff = curr_gray ^ next_gray
            bit_changed_from_right = int(np.log2(diff))
            wire_to_flip = img_wires[n - 1 - bit_changed_from_right]
            qml.PauliX(wires=wire_to_flip)

    last_gray_bin = format(gray_seq[-1], f'0{n}b')
    for i, bit in enumerate(last_gray_bin):
        if bit == '0':
            qml.PauliX(wires=img_wires[i])

## Parametros del CC
n_pixels = 64
n_image_wires = 6
n_estimation_wires = 8
total_wires = n_estimation_wires + n_image_wires

dev = qml.device('default.qubit', wires=total_wires)

@qml.qnode(dev)
def edge_detection_circuit(flat_p1, flat_p2):
    est_wires = list(range(n_estimation_wires))
    tgt_wires = list(range(n_estimation_wires, total_wires))

    for w in est_wires + tgt_wires:
        qml.Hadamard(wires=w)

    for i, est_wire in enumerate(reversed(est_wires)):
        power = 2**i
        apply_dual_phases_with_gray_code(flat_p1, flat_p2, tgt_wires, est_wire, power)

    qml.adjoint(qml.QFT)(wires=est_wires)
    return qml.probs(wires=est_wires + tgt_wires)

### Decodificación.
def extract_gradient_magnitude(probs, shape, threshold=0.001):
    weighted_mag_sum = np.zeros(shape, dtype=float)
    prob_sum = np.zeros(shape, dtype=float)

    for k, p in enumerate(probs):
        if p > threshold:
            bin_k = format(k, f'0{total_wires}b')
            est_int = int(bin_k[:n_estimation_wires], 2)
            pixel_idx = int(bin_k[n_estimation_wires:], 2)

            if pixel_idx < n_pixels:
                row, col = np.unravel_index(pixel_idx, shape)
                raw_val = (est_int / (2**n_estimation_wires)) * 255.0

                # Compensación del escalamiento a media fase (x2)
                edge_magnitude = 2.0 * min(raw_val, 255.0 - raw_val)

                weighted_mag_sum[row, col] += p * edge_magnitude
                prob_sum[row, col] += p

    safe_prob_sum = np.where(prob_sum == 0, 1.0, prob_sum)
    return weighted_mag_sum / safe_prob_sum

## Cargar dataset y calcular Sobel clasico y cuántico.
digits = load_digits()
images_to_test = digits.images[:5]
targets = digits.target[:5]

fig, axes = plt.subplots(5, 4, figsize=(14, 16))

for idx, raw_img in enumerate(images_to_test):
    raw_img = (raw_img / 16.0) * 255.0

    # Preprocesamiento
    shifted_x = np.roll(raw_img, shift=1, axis=1); shifted_x[:, 0] = 0
    shifted_y = np.roll(raw_img, shift=1, axis=0); shifted_y[0, :] = 0

    # Escalamiento de media fase.
    phases_base = (raw_img.flatten() / 255.0) * np.pi
    phases_neg_x = (-shifted_x.flatten() / 255.0) * np.pi
    phases_neg_y = (-shifted_y.flatten() / 255.0) * np.pi

    # Sobel cuantico.
    print(f"Ejecutando QPE (Sobel) para dígito {targets[idx]} ({idx+1}/5)...")
    probs_x = edge_detection_circuit(phases_base, phases_neg_x)
    probs_y = edge_detection_circuit(phases_base, phases_neg_y)

    # Decodificación cuántica
    q_gx = extract_gradient_magnitude(probs_x, raw_img.shape)
    q_gy = extract_gradient_magnitude(probs_y, raw_img.shape)

    # Fusión híbrida (Norma L2)
    quantum_sobel = np.sqrt(q_gx**2 + q_gy**2)

    # Ground Truth (clásico)
    c_gx = np.abs(raw_img - shifted_x)
    c_gy = np.abs(raw_img - shifted_y)
    classic_sobel = np.sqrt(c_gx**2 + c_gy**2)

    # Métrica (MAE)
    mae_score = mean_absolute_error(classic_sobel.flatten(), quantum_sobel.flatten())
    print(f"  -> MAE Sobel Total: {mae_score:.4f}")

    # Visualización
    axes[idx, 0].imshow(raw_img, cmap='gray', vmin=0, vmax=255)
    axes[idx, 0].set_title(f"Original: {targets[idx]}")
    axes[idx, 0].axis('off')

    axes[idx, 1].imshow(np.clip(q_gx + q_gy, 0, 255), cmap='gray', vmin=0, vmax=255)
    axes[idx, 1].set_title("QED components\n($|G_x| + |G_y|$)")
    axes[idx, 1].axis('off')

    axes[idx, 2].imshow(np.clip(classic_sobel, 0, 255), cmap='gray', vmin=0, vmax=255)
    axes[idx, 2].set_title("Classic Sobel\n$\sqrt{G_x^2 + G_y^2}$")
    axes[idx, 2].axis('off')

    axes[idx, 3].imshow(np.clip(quantum_sobel, 0, 255), cmap='gray', vmin=0, vmax=255)
    axes[idx, 3].set_title(f"Q-PIPE Sobel \nMAE: {mae_score:.2f}")
    axes[idx, 3].axis('off')

plt.tight_layout()
plt.savefig("sobel_edge_detection_mnist.png", dpi=600)
plt.savefig("sobel_edge_detection_mnist.eps")
plt.show()
print("Procesamiento híbrido Sobel finalizado.")

"""# Proof of concept: Detección de bordes"""

### (1) Oráculo dual Optimizado (Gray) ###
def apply_dual_phases_with_gray_code(flat_phases_1, flat_phases_2, img_wires, est_wire, power):
    ## Recorre la imagen una sola vez usando Código Gray, inyectando las fases de ambas imágenes en cada posición.
    n = len(img_wires)
    total_states = 2**n

    # Secuencia Gray: g_i = i XOR (i >> 1)
    gray_seq = [i ^ (i >> 1) for i in range(total_states)]

    # Mapeo Inicial: de |00...0> a |11...1>
    for w in img_wires:
        qml.PauliX(wires=w)

    target_wire = img_wires[-1]
    control_wires = [est_wire] + list(img_wires[:-1])

    # Recorrido Único
    for step in range(total_states):
        curr_gray = gray_seq[step]
        pixel_idx = curr_gray

        # Inyección de Fases (si el píxel existe en las dimensiones reales)
        if pixel_idx < len(flat_phases_1):
            phi1 = flat_phases_1[pixel_idx]
            phi2 = flat_phases_2[pixel_idx]

            # Codificación Imagen 1
            if abs(phi1) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi1 * power, wires=target_wire)

            # Codificación Imagen 2 (Acumulación en el mismo paso)
            if abs(phi2) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi2 * power, wires=target_wire)

        # Transición Gray (Una sola compuerta X)
        if step < total_states - 1:
            next_gray = gray_seq[step + 1]
            diff = curr_gray ^ next_gray
            bit_changed_from_right = int(np.log2(diff))
            wire_to_flip = img_wires[n - 1 - bit_changed_from_right]
            qml.PauliX(wires=wire_to_flip)

    # Uncompute Final para restaurar la base topológica
    last_gray_bin = format(gray_seq[-1], f'0{n}b')
    for i, bit in enumerate(last_gray_bin):
        if bit == '0':
            qml.PauliX(wires=img_wires[i])

# Imagen de prueba: Un bloque sólido sobre fondo oscuro (genera bordes claros)
# Dimensiones: 4x4
raw_img = np.array([[0,   0,   0,   0],
                    [0, 200, 200,   0],
                    [0, 200, 200,   0],
                    [0,   0,   0,   0]])

# Crear la imagen desplazada horizontalmente (padding con ceros a la izquierda)
shifted_img = np.roll(raw_img, shift=1, axis=1)
# Opcional: Limpiar la primera columna para no tener bordes "envueltos"
shifted_img[:, 0] = 0

# Normalización a fases.
# IMPORTANTE: La segunda imagen lleva signo NEGATIVO para efectuar la resta.
phases_base = (raw_img.flatten() / 255.0) * (2 * np.pi)
phases_shifted_neg = (-shifted_img.flatten() / 255.0) * (2 * np.pi)

n_pixels = raw_img.size
n_image_wires = int(np.ceil(np.log2(n_pixels)))
n_estimation_wires = 8
total_wires = n_estimation_wires + n_image_wires

dev = qml.device('default.qubit', wires=total_wires)

@qml.qnode(dev)
def edge_detection_circuit(flat_p1, flat_p2):
    est_wires = list(range(n_estimation_wires))
    tgt_wires = list(range(n_estimation_wires, total_wires))

    for w in est_wires + tgt_wires:
        qml.Hadamard(wires=w)

    for i, est_wire in enumerate(reversed(est_wires)):
        power = 2**i
        apply_dual_phases_with_gray_code(flat_p1, flat_p2, tgt_wires, est_wire, power)

    qml.adjoint(qml.QFT)(wires=est_wires)
    return qml.probs(wires=est_wires + tgt_wires)

### MAIN ###
print(f"Ejecutando QPE para Detección de Bordes...")
probs = edge_detection_circuit(phases_base, phases_shifted_neg)

print("\n Resultados del Filtro de Contorno")
print(f"{'Coord':<10} {'I_orig':<8} {'I_shift':<10} {'Gradiente_QPE':<15} {'Significado'}")
print("-" * 65)

for k, p in enumerate(probs):
    if p > 0.05:
        bin_k = format(k, f'0{total_wires}b')
        est_int = int(bin_k[:n_estimation_wires], 2)
        pixel_idx = int(bin_k[n_estimation_wires:], 2)

        if pixel_idx >= n_pixels: continue

        row, col = np.unravel_index(pixel_idx, raw_img.shape)
        val_orig = raw_img[row, col]
        val_shift = shifted_img[row, col]

        # Recuperación con aritmética modular cuántica
        recovered_val = (est_int / (2**n_estimation_wires)) * 255

        # Interpretación del desbordamiento (Overflow)
        # Si el resultado es muy cercano a 255, es un gradiente negativo (ej. 0 - 200 = -200 -> modulo 256 -> 56)
        # Para simplificar la vista, convertimos a magnitud del borde
        edge_magnitude = recovered_val
        meaning = "Área Plana"
        if recovered_val > 5 and recovered_val < 250:
            meaning = "BORDE DETECTADO"

        print(f"({row},{col})       {val_orig:<8} {val_shift:<10} {recovered_val:.2f}           {meaning}")

def apply_dual_phases_with_gray_code(flat_phases_1, flat_phases_2, img_wires, est_wire, power):
    n = len(img_wires)
    total_states = 2**n
    gray_seq = [i ^ (i >> 1) for i in range(total_states)]

    for w in img_wires:
        qml.PauliX(wires=w)

    target_wire = img_wires[-1]
    control_wires = [est_wire] + list(img_wires[:-1])

    for step in range(total_states):
        curr_gray = gray_seq[step]
        pixel_idx = curr_gray

        if pixel_idx < len(flat_phases_1):
            phi1 = flat_phases_1[pixel_idx]
            phi2 = flat_phases_2[pixel_idx]

            if abs(phi1) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi1 * power, wires=target_wire)
            if abs(phi2) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi2 * power, wires=target_wire)

        if step < total_states - 1:
            next_gray = gray_seq[step + 1]
            diff = curr_gray ^ next_gray
            bit_changed_from_right = int(np.log2(diff))
            wire_to_flip = img_wires[n - 1 - bit_changed_from_right]
            qml.PauliX(wires=wire_to_flip)

    last_gray_bin = format(gray_seq[-1], f'0{n}b')
    for i, bit in enumerate(last_gray_bin):
        if bit == '0':
            qml.PauliX(wires=img_wires[i])

### Imagen de prueba ###
raw_img = np.array([[0,   0,   0,   0],
                    [0, 200, 200,   0],
                    [0, 200, 200,   0],
                    [0,   0,   0,   0]])

shifted_img = np.roll(raw_img, shift=1, axis=1)
shifted_img[:, 0] = 0

phases_base = (raw_img.flatten() / 255.0) * (2 * np.pi)
phases_shifted_neg = (-shifted_img.flatten() / 255.0) * (2 * np.pi)

n_pixels = raw_img.size
n_image_wires = int(np.ceil(np.log2(n_pixels)))
n_estimation_wires = 8
total_wires = n_estimation_wires + n_image_wires

dev = qml.device('default.qubit', wires=total_wires)

@qml.qnode(dev)
def edge_detection_circuit(flat_p1, flat_p2):
    est_wires = list(range(n_estimation_wires))
    tgt_wires = list(range(n_estimation_wires, total_wires))

    for w in est_wires + tgt_wires:
        qml.Hadamard(wires=w)

    for i, est_wire in enumerate(reversed(est_wires)):
        power = 2**i
        apply_dual_phases_with_gray_code(flat_p1, flat_p2, tgt_wires, est_wire, power)

    qml.adjoint(qml.QFT)(wires=est_wires)
    return qml.probs(wires=est_wires + tgt_wires)

### Post procesamiento ###
print("Ejecutando QPE para Detección de Bordes...")
probs = edge_detection_circuit(phases_base, phases_shifted_neg)

# Matriz vacía para reconstruir la imagen de bordes
quantum_edge_img = np.zeros_like(raw_img, dtype=float)

for k, p in enumerate(probs):
    if p > 0.05:
        bin_k = format(k, f'0{total_wires}b')
        est_int = int(bin_k[:n_estimation_wires], 2)
        pixel_idx = int(bin_k[n_estimation_wires:], 2)

        if pixel_idx < n_pixels:
            row, col = np.unravel_index(pixel_idx, raw_img.shape)
            # Valor cíclico crudo [0, 255]
            raw_val = (est_int / (2**n_estimation_wires)) * 255
            # Cálculo de la magnitud absoluta del gradiente.
            edge_magnitude = min(raw_val, 256 - raw_val)
            quantum_edge_img[row, col] = edge_magnitude

### Visualización ###
fig, axes = plt.subplots(1, 3, figsize=(15, 5))

# Función auxiliar para plotear con texto
def plot_matrix(ax, matrix, title):
    cax = ax.imshow(matrix, cmap='gray', vmin=0, vmax=255)
    ax.set_title(title, fontsize=14)
    ax.axis('off')

    # Anotar valores numéricos sobre cada píxel
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            val = int(matrix[i, j])
            color = 'white' if val < 128 else 'black'
            ax.text(j, i, str(val), ha='center', va='center', color=color, fontsize=12, fontweight='bold')

plot_matrix(axes[0], raw_img, "Original Image\n$I(x,y)$")
plot_matrix(axes[1], shifted_img, "Displaced Image\n$I(x, y-1)$")

# Para que el borde se note claramente en escala de grises, podemos escalar la magnitud.
plot_matrix(axes[2], np.clip(quantum_edge_img, 0, 255), "Quantum Edge Detection (QED) \n $\Delta\phi$")
# plot_matrix(axes[2], np.clip(quantum_edge_img * 2, 0, 255), "Detección de Bordes (QPE)\nMagnitud $\Delta\phi$") ## Escalados X 2.

# plt.tight_layout()
plt.savefig("edge_detection_circuit.png", dpi=600)
plt.savefig("edge_detection_circuit.eps")
plt.show()

"""## Ejemplo de detección de bordes usando MNIST."""

### CORRIMIENTO HORIZONTAL ###
def apply_dual_phases_with_gray_code(flat_phases_1, flat_phases_2, img_wires, est_wire, power):
    n = len(img_wires)
    total_states = 2**n
    gray_seq = [i ^ (i >> 1) for i in range(total_states)]

    for w in img_wires:
        qml.PauliX(wires=w)

    target_wire = img_wires[-1]
    control_wires = [est_wire] + list(img_wires[:-1])

    for step in range(total_states):
        curr_gray = gray_seq[step]
        pixel_idx = curr_gray

        if pixel_idx < len(flat_phases_1):
            phi1 = flat_phases_1[pixel_idx]
            phi2 = flat_phases_2[pixel_idx]

            if abs(phi1) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi1 * power, wires=target_wire)
            if abs(phi2) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi2 * power, wires=target_wire)

        if step < total_states - 1:
            next_gray = gray_seq[step + 1]
            diff = curr_gray ^ next_gray
            bit_changed_from_right = int(np.log2(diff))
            wire_to_flip = img_wires[n - 1 - bit_changed_from_right]
            qml.PauliX(wires=wire_to_flip)

    last_gray_bin = format(gray_seq[-1], f'0{n}b')
    for i, bit in enumerate(last_gray_bin):
        if bit == '0':
            qml.PauliX(wires=img_wires[i])

# ==========================================
# Circuito cuántico
# ==========================================
n_pixels = 64
n_image_wires = 6
n_estimation_wires = 8
total_wires = n_estimation_wires + n_image_wires

dev = qml.device('default.qubit', wires=total_wires)

@qml.qnode(dev)
def edge_detection_circuit(flat_p1, flat_p2):
    est_wires = list(range(n_estimation_wires))
    tgt_wires = list(range(n_estimation_wires, total_wires))

    for w in est_wires + tgt_wires:
        qml.Hadamard(wires=w)

    for i, est_wire in enumerate(reversed(est_wires)):
        power = 2**i
        apply_dual_phases_with_gray_code(flat_p1, flat_p2, tgt_wires, est_wire, power)

    qml.adjoint(qml.QFT)(wires=est_wires)
    return qml.probs(wires=est_wires + tgt_wires)

# ==========================================
# Carga de Datos y Procesamiento
# ==========================================
digits = load_digits()
images_to_test = digits.images[:5]
targets = digits.target[:5]

# Ampliamos a 4 columnas y ajustamos el tamaño de la figura
fig, axes = plt.subplots(5, 4, figsize=(14, 16))

for idx, raw_img in enumerate(images_to_test):
    # Normalizar
    raw_img = (raw_img / 16.0) * 255.0

    # Preprocesamiento clásico: desplazamiento horizontal
    shifted_img = np.roll(raw_img, shift=1, axis=1)
    shifted_img[:, 0] = 0

    # --- Cálculo Analítico (Ground Truth) ---
    classical_gradient = np.abs(raw_img - shifted_img)

    phases_base = (raw_img.flatten() / 255.0) * (2 * np.pi)
    phases_shifted_neg = (-shifted_img.flatten() / 255.0) * (2 * np.pi)

    print(f"Calculando circuito cuántico para el dígito {targets[idx]} ({idx+1}/5)...")
    probs = edge_detection_circuit(phases_base, phases_shifted_neg)

    quantum_edge_img = np.zeros_like(raw_img, dtype=float)

    for k, p in enumerate(probs):
        if p > 0.01:
            bin_k = format(k, f'0{total_wires}b')
            est_int = int(bin_k[:n_estimation_wires], 2)
            pixel_idx = int(bin_k[n_estimation_wires:], 2)

            if pixel_idx < n_pixels:
                row, col = np.unravel_index(pixel_idx, raw_img.shape)
                raw_val = (est_int / (2**n_estimation_wires)) * 255.0

                edge_magnitude = min(raw_val, 256.0 - raw_val)
                quantum_edge_img[row, col] = edge_magnitude

    # --- Cálculo de Métrica ---
    mae_score = mean_absolute_error(classical_gradient.flatten(), quantum_edge_img.flatten())
    print(f"  -> MAE Horizontal: {mae_score:.4f}")

    # Visualización
    axes[idx, 0].imshow(raw_img, cmap='gray', vmin=0, vmax=255)
    axes[idx, 0].set_title(f"Original: {targets[idx]}")
    axes[idx, 0].axis('off')

    axes[idx, 1].imshow(shifted_img, cmap='gray', vmin=0, vmax=255)
    axes[idx, 1].set_title("Displaced")
    axes[idx, 1].axis('off')

    # Añadimos la columna del gradiente clásico
    axes[idx, 2].imshow(classical_gradient, cmap='gray', vmin=0, vmax=255)
    axes[idx, 2].set_title("Classical Gradient")
    axes[idx, 2].axis('off')

    axes[idx, 3].imshow(np.clip(quantum_edge_img, 0, 255), cmap='gray', vmin=0, vmax=255)
    axes[idx, 3].set_title(f"QED\nMAE: {mae_score:.2f}")
    axes[idx, 3].axis('off')

plt.tight_layout()
plt.savefig("edge_detection_circuit_mnist_horizontal.png", dpi=600)
plt.savefig("edge_detection_circuit_mnist_horizontal.eps")
plt.show()
print("Procesamiento cuántico finalizado.")

"""### MAE desplazamiento vertical"""

### DESPLAZAMIENTO VERTICAL ###
def apply_dual_phases_with_gray_code(flat_phases_1, flat_phases_2, img_wires, est_wire, power):
    n = len(img_wires)
    total_states = 2**n
    gray_seq = [i ^ (i >> 1) for i in range(total_states)]

    for w in img_wires:
        qml.PauliX(wires=w)

    target_wire = img_wires[-1]
    control_wires = [est_wire] + list(img_wires[:-1])

    for step in range(total_states):
        curr_gray = gray_seq[step]
        pixel_idx = curr_gray

        if pixel_idx < len(flat_phases_1):
            phi1 = flat_phases_1[pixel_idx]
            phi2 = flat_phases_2[pixel_idx]

            if abs(phi1) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi1 * power, wires=target_wire)
            if abs(phi2) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi2 * power, wires=target_wire)

        if step < total_states - 1:
            next_gray = gray_seq[step + 1]
            diff = curr_gray ^ next_gray
            bit_changed_from_right = int(np.log2(diff))
            wire_to_flip = img_wires[n - 1 - bit_changed_from_right]
            qml.PauliX(wires=wire_to_flip)

    last_gray_bin = format(gray_seq[-1], f'0{n}b')
    for i, bit in enumerate(last_gray_bin):
        if bit == '0':
            qml.PauliX(wires=img_wires[i])

# ==========================================
# Configuración del Dispositivo Cuántico
# ==========================================
n_pixels = 64
n_image_wires = 6
n_estimation_wires = 8
total_wires = n_estimation_wires + n_image_wires

dev = qml.device('default.qubit', wires=total_wires)

@qml.qnode(dev)
def edge_detection_circuit(flat_p1, flat_p2):
    est_wires = list(range(n_estimation_wires))
    tgt_wires = list(range(n_estimation_wires, total_wires))

    for w in est_wires + tgt_wires:
        qml.Hadamard(wires=w)

    for i, est_wire in enumerate(reversed(est_wires)):
        power = 2**i
        apply_dual_phases_with_gray_code(flat_p1, flat_p2, tgt_wires, est_wire, power)

    qml.adjoint(qml.QFT)(wires=est_wires)
    return qml.probs(wires=est_wires + tgt_wires)

# ==========================================
# Procesamiento y Evaluación (Gradiente Vertical)
# ==========================================
digits = load_digits()
images_to_test = digits.images[:5]
targets = digits.target[:5]

fig, axes = plt.subplots(5, 4, figsize=(14, 16))

for idx, raw_img in enumerate(images_to_test):
    # Normalización
    raw_img = (raw_img / 16.0) * 255.0

    # Preprocesamiento: Desplazamiento VERTICAL (axis=0)
    shifted_img_y = np.roll(raw_img, shift=1, axis=0)
    shifted_img_y[0, :] = 0  # Limpiar la primera fila (bordes envueltos)

    phases_base = (raw_img.flatten() / 255.0) * (2 * np.pi)
    phases_shifted_neg = (-shifted_img_y.flatten() / 255.0) * (2 * np.pi)

    # 1. Cálculo Clásico (Ground Truth)
    classical_gradient = np.abs(raw_img - shifted_img_y)

    # 2. Cálculo Cuántico (QPE)
    print(f"Calculando circuito para el dígito {targets[idx]} ({idx+1}/5)...")
    probs = edge_detection_circuit(phases_base, phases_shifted_neg)

    quantum_edge_img = np.zeros_like(raw_img, dtype=float)
    for k, p in enumerate(probs):
        if p > 0.01:
            bin_k = format(k, f'0{total_wires}b')
            est_int = int(bin_k[:n_estimation_wires], 2)
            pixel_idx = int(bin_k[n_estimation_wires:], 2)

            if pixel_idx < n_pixels:
                row, col = np.unravel_index(pixel_idx, raw_img.shape)
                raw_val = (est_int / (2**n_estimation_wires)) * 255.0
                edge_magnitude = min(raw_val, 256.0 - raw_val)
                quantum_edge_img[row, col] = edge_magnitude

    # 3. Evaluación de Métrica (MAE)
    mae_score = mean_absolute_error(classical_gradient.flatten(), quantum_edge_img.flatten())
    print(f"  -> Error Absoluto Medio (MAE): {mae_score:.4f} niveles de intensidad")

    # 4. Visualización Comparativa
    axes[idx, 0].imshow(raw_img, cmap='gray', vmin=0, vmax=255)
    axes[idx, 0].set_title(f"Original: {targets[idx]}")
    axes[idx, 0].axis('off')

    axes[idx, 1].imshow(shifted_img_y, cmap='gray', vmin=0, vmax=255)
    axes[idx, 1].set_title("Displaced")
    axes[idx, 1].axis('off')

    axes[idx, 2].imshow(classical_gradient, cmap='gray', vmin=0, vmax=255)
    axes[idx, 2].set_title(f"Classical Gradient")
    axes[idx, 2].axis('off')

    axes[idx, 3].imshow(quantum_edge_img, cmap='gray', vmin=0, vmax=255)
    axes[idx, 3].set_title(f"QED\nMAE: {mae_score:.2f}")
    axes[idx, 3].axis('off')

plt.tight_layout()
plt.savefig("edge_detection_circuit_mnist_vertical.png", dpi=600)
plt.savefig("edge_detection_circuit_mnist_vertical.eps")
plt.show()
print("Evaluación finalizada.")

"""### Operador de Sobel"""

### EVALUACIÓN APROXIMADA DEL OPERADOR DE SOBEL ###
def apply_dual_phases_with_gray_code(flat_phases_1, flat_phases_2, img_wires, est_wire, power):
    n = len(img_wires)
    total_states = 2**n
    gray_seq = [i ^ (i >> 1) for i in range(total_states)]

    for w in img_wires:
        qml.PauliX(wires=w)

    target_wire = img_wires[-1]
    control_wires = [est_wire] + list(img_wires[:-1])

    for step in range(total_states):
        curr_gray = gray_seq[step]
        pixel_idx = curr_gray

        if pixel_idx < len(flat_phases_1):
            phi1 = flat_phases_1[pixel_idx]
            phi2 = flat_phases_2[pixel_idx]

            if abs(phi1) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi1 * power, wires=target_wire)
            if abs(phi2) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi2 * power, wires=target_wire)

        if step < total_states - 1:
            next_gray = gray_seq[step + 1]
            diff = curr_gray ^ next_gray
            bit_changed_from_right = int(np.log2(diff))
            wire_to_flip = img_wires[n - 1 - bit_changed_from_right]
            qml.PauliX(wires=wire_to_flip)

    last_gray_bin = format(gray_seq[-1], f'0{n}b')
    for i, bit in enumerate(last_gray_bin):
        if bit == '0':
            qml.PauliX(wires=img_wires[i])

# ==========================================
# Circuito Cuántico QPE
# ==========================================
n_pixels = 64
n_image_wires = 6
n_estimation_wires = 8
total_wires = n_estimation_wires + n_image_wires

dev = qml.device('default.qubit', wires=total_wires)

@qml.qnode(dev)
def edge_detection_circuit(flat_p1, flat_p2):
    est_wires = list(range(n_estimation_wires))
    tgt_wires = list(range(n_estimation_wires, total_wires))

    for w in est_wires + tgt_wires:
        qml.Hadamard(wires=w)

    for i, est_wire in enumerate(reversed(est_wires)):
        power = 2**i
        apply_dual_phases_with_gray_code(flat_p1, flat_p2, tgt_wires, est_wire, power)

    qml.adjoint(qml.QFT)(wires=est_wires)
    return qml.probs(wires=est_wires + tgt_wires)

# Función auxiliar de decodificación
def decode_probabilities(probs, shape):
    quantum_edge = np.zeros(shape, dtype=float)
    for k, p in enumerate(probs):
        if p > 0.01:
            bin_k = format(k, f'0{total_wires}b')
            est_int = int(bin_k[:n_estimation_wires], 2)
            pixel_idx = int(bin_k[n_estimation_wires:], 2)

            if pixel_idx < n_pixels:
                row, col = np.unravel_index(pixel_idx, shape)
                raw_val = (est_int / (2**n_estimation_wires)) * 255.0
                edge_magnitude = min(raw_val, 256.0 - raw_val)
                quantum_edge[row, col] = edge_magnitude
    return quantum_edge

# ==========================================
# Procesamiento Híbrido: Aproximación Sobel
# ==========================================
digits = load_digits()
images_to_test = digits.images[:5]
targets = digits.target[:5]

fig, axes = plt.subplots(5, 4, figsize=(14, 16))

for idx, raw_img in enumerate(images_to_test):
    # Normalización
    raw_img = (raw_img / 16.0) * 255.0
    phases_base = (raw_img.flatten() / 255.0) * (2 * np.pi)

    # Preprocesamiento Clásico (Desplazamientos)
    shifted_x = np.roll(raw_img, shift=1, axis=1); shifted_x[:, 0] = 0
    shifted_y = np.roll(raw_img, shift=1, axis=0); shifted_y[0, :] = 0

    phases_neg_x = (-shifted_x.flatten() / 255.0) * (2 * np.pi)
    phases_neg_y = (-shifted_y.flatten() / 255.0) * (2 * np.pi)

    # 1. Ejecución Cuántica (Dos llamadas al oráculo QPE)
    print(f"Ejecutando QPE (Sobel) para dígito {targets[idx]} ({idx+1}/5)...")
    probs_x = edge_detection_circuit(phases_base, phases_neg_x)
    probs_y = edge_detection_circuit(phases_base, phases_neg_y)

    # Decodificación Cuántica
    q_gx = decode_probabilities(probs_x, raw_img.shape)
    q_gy = decode_probabilities(probs_y, raw_img.shape)

    # Fusión Híbrida (Magnitud Sobel Cuántica)
    quantum_sobel = np.sqrt(q_gx**2 + q_gy**2)

    # 2. Ejecución Clásica Analítica (Ground Truth)
    c_gx = np.abs(raw_img - shifted_x)
    c_gy = np.abs(raw_img - shifted_y)
    classic_sobel = np.sqrt(c_gx**2 + c_gy**2)

    # Evaluación de Métrica (MAE)
    mae_score = mean_absolute_error(classic_sobel.flatten(), quantum_sobel.flatten())
    print(f"  -> MAE Sobel: {mae_score:.4f}")

    # Visualización
    axes[idx, 0].imshow(raw_img, cmap='gray', vmin=0, vmax=255)
    axes[idx, 0].set_title(f"Original: {targets[idx]}")
    axes[idx, 0].axis('off')

    # Componentes Cuánticos individuales
    axes[idx, 1].imshow(np.clip(q_gx + q_gy, 0, 255), cmap='gray', vmin=0, vmax=255)
    axes[idx, 1].set_title("Components QED\n($|G_x| + |G_y|$)")
    axes[idx, 1].axis('off')

    axes[idx, 2].imshow(np.clip(classic_sobel, 0, 255), cmap='gray', vmin=0, vmax=255)
    axes[idx, 2].set_title("Classic Sobel\n$\sqrt{G_x^2 + G_y^2}$")
    axes[idx, 2].axis('off')

    axes[idx, 3].imshow(np.clip(quantum_sobel, 0, 255), cmap='gray', vmin=0, vmax=255)
    axes[idx, 3].set_title(f"Sobel QED\nMAE: {mae_score:.2f}")
    axes[idx, 3].axis('off')

plt.tight_layout()
plt.savefig("sobel_edge_detection_mnist.png", dpi=600)
plt.savefig("sobel_edge_detection_mnist.eps")
plt.show()
print("Procesamiento cuántico de Sobel finalizado.")

"""# Generalizaciones

## Gen. cod. 2 imagenes (suma) OPTIMIZADO usando código Gray
"""

### (1) Oráculo dual Optimizado (Gray) ###
def apply_dual_phases_with_gray_code(flat_phases_1, flat_phases_2, img_wires, est_wire, power):
    """Recorre la imagen una sola vez usando Código Gray, inyectando las fases de ambas imágenes en cada parada."""
    n = len(img_wires)
    total_states = 2**n

    # Secuencia Gray: g_i = i XOR (i >> 1)
    gray_seq = [i ^ (i >> 1) for i in range(total_states)]

    # Mapeo Inicial: de |00...0> a |11...1>
    for w in img_wires:
        qml.PauliX(wires=w)

    target_wire = img_wires[-1]
    control_wires = [est_wire] + list(img_wires[:-1])

    # Recorrido Único
    for step in range(total_states):
        curr_gray = gray_seq[step]
        pixel_idx = curr_gray

        # Inyección de Fases (si el píxel existe en las dimensiones reales)
        if pixel_idx < len(flat_phases_1):
            phi1 = flat_phases_1[pixel_idx]
            phi2 = flat_phases_2[pixel_idx]

            # Codificación Imagen 1
            if abs(phi1) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi1 * power, wires=target_wire)

            # Codificación Imagen 2 (Acumulación en el mismo paso)
            if abs(phi2) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi2 * power, wires=target_wire)

        # Transición Gray (Una sola compuerta X)
        if step < total_states - 1:
            next_gray = gray_seq[step + 1]
            diff = curr_gray ^ next_gray
            bit_changed_from_right = int(np.log2(diff))
            wire_to_flip = img_wires[n - 1 - bit_changed_from_right]
            qml.PauliX(wires=wire_to_flip)

    # Uncompute Final para restaurar la base topológica
    last_gray_bin = format(gray_seq[-1], f'0{n}b')
    for i, bit in enumerate(last_gray_bin):
        if bit == '0':
            qml.PauliX(wires=img_wires[i])

### (2) Configuración y Circuito
# Imágenes 2x4 (8 píxeles)
raw_img1 = np.array([[10,  31, 0,   10],
                     [9,   0,  200, 0]])

raw_img2 = np.array([[25, 54,  87,  6],
                     [10, 20,  54,  1]])

n_pixels = raw_img1.size
n_image_wires = int(np.ceil(np.log2(n_pixels)))
n_estimation_wires = 8
total_wires = n_estimation_wires + n_image_wires

dev = qml.device('default.qubit', wires=total_wires)

@qml.qnode(dev)
def dual_gray_encoding_circuit(flat_p1, flat_p2):
    est_wires = list(range(n_estimation_wires))
    tgt_wires = list(range(n_estimation_wires, total_wires))

    ## (a) Superposición
    for w in est_wires + tgt_wires:
        qml.Hadamard(wires=w)

    qml.Barrier()

    # (b) Retroceso de Fase Dual Centralizado
    for i, est_wire in enumerate(reversed(est_wires)):
        power = 2**i
        apply_dual_phases_with_gray_code(flat_p1, flat_p2, tgt_wires, est_wire, power)
        qml.Barrier()

    # (c) Recuperación
    qml.adjoint(qml.QFT)(wires=est_wires)

    return qml.probs(wires=est_wires + tgt_wires)

### MAIN ###
flat_phases_1 = (raw_img1.flatten() / 255.0) * (2 * np.pi)
flat_phases_2 = (raw_img2.flatten() / 255.0) * (2 * np.pi)

print(f"Ejecutando QPE Dual (Código Gray) para {raw_img1.shape}...")
probs = dual_gray_encoding_circuit(flat_phases_1, flat_phases_2)

## Resultados ##
def analyze_results(probabilities, image_shape, threshold=0.05):
    print(f"\n{'Posición (Bin)':<15} {'Suma Esperada':<15} {'Valor Recuperado':<15} {'Probabilidad'}")
    print("-" * 65)

    for k, p in enumerate(probabilities):
        if p > threshold:
            bin_k = format(k, f'0{total_wires}b')
            est_bin = bin_k[:n_estimation_wires]
            img_bin = bin_k[n_estimation_wires:]

            est_int = int(est_bin, 2)
            pixel_idx = int(img_bin, 2)

            if pixel_idx >= np.prod(image_shape):
                continue

            row, col = np.unravel_index(pixel_idx, image_shape)
            val1 = raw_img1[row, col]
            val2 = raw_img2[row, col]
            expected_sum = val1 + val2

            recovered_val = (est_int / (2**n_estimation_wires)) * 255
            print(f"|{img_bin}> ({row},{col})    {val1}+{val2}={expected_sum:<7} {recovered_val:.2f}           {p:.4f}")

analyze_results(probs, raw_img1.shape)
fig, ax = qml.draw_mpl(dual_gray_encoding_circuit)(flat_phases_1, flat_phases_2)

### Perfilado de Recursos (Métricas Reales)
circuit_specs = qml.specs(dual_gray_encoding_circuit)(flat_phases_1, flat_phases_2)
resources = circuit_specs['resources']

print("\n=== Perfilado del Circuito ===")
print(f"Total de operaciones brutas: {resources.num_gates}")
print(f"Profundidad del circuito (Depth): {resources.depth}")
print("\nDesglose de compuertas utilizadas:")
for gate, count in resources.gate_types.items():
    print(f" - {gate}: {count}")

"""## Gen. cod. 1 imagen (n x m) OPTIMIZADO usando código Gray"""

### (1) Normalización de imagen de 0 a 2pi, y numero de wires.
def get_image_setup(raw_img_array):
    flat_image = raw_img_array.flatten()
    n_pixels = len(flat_image)
    n_image_wires = int(np.ceil(np.log2(n_pixels)))
    phases = (flat_image / 255.0) * (2 * np.pi)
    return phases, n_image_wires

### (2) Oráculo optimizado (Código Gray)
def apply_phases_with_gray_code(flat_phases, img_wires, est_wire, power):
    """
    Aplica las fases de toda la imagen utilizando una trayectoria de Código Gray.
    Elimina la necesidad de hacer uncompute/compute completo por cada píxel.
    """
    n = len(img_wires)
    total_states = 2**n

    # Generación de la secuencia Gray: g_i = i XOR (i >> 1)
    gray_seq = [i ^ (i >> 1) for i in range(total_states)]

    # 1. Mapeo Inicial: Convertir el estado inicial |00...0> al target |11...1>
    # Empezamos en gray_seq[0] = 0. Invertimos todos los cables.
    for w in img_wires:
        qml.PauliX(wires=w)

    target_wire = img_wires[-1]
    control_wires = [est_wire] + list(img_wires[:-1])

    # 2. Recorrido de la secuencia
    for step in range(total_states):
        curr_gray = gray_seq[step]
        pixel_idx = curr_gray

        # Inyectar la fase si el píxel existe y no es cero (ahorra compuertas de fase)
        # Nota: NO saltamos el paso en el ciclo, ya que la secuencia Gray de compuertas X debe mantenerse.
        if pixel_idx < len(flat_phases):
            phi = flat_phases[pixel_idx]
            if abs(phi) > 1e-5:
                current_phi = phi * power
                qml.ctrl(qml.PhaseShift, control=control_wires)(current_phi, wires=target_wire)

        # 3. Transición al siguiente estado Gray usando una sola compuerta X
        if step < total_states - 1:
            next_gray = gray_seq[step + 1]
            diff = curr_gray ^ next_gray

            # Identificar la posición del bit que cambió (0-indexado desde LSB)
            bit_changed_from_right = int(np.log2(diff))
            # Mapear a los cables de imagen (MSB a LSB)
            wire_to_flip = img_wires[n - 1 - bit_changed_from_right]

            qml.PauliX(wires=wire_to_flip)

    # 4. Uncompute Final
    # Revertir los cables a su estado base original para no corromper la QFT posterior.
    # Los cables que terminaron invertidos son aquellos correspondientes a los ceros en el último estado Gray.
    last_gray_bin = format(gray_seq[-1], f'0{n}b')
    for i, bit in enumerate(last_gray_bin):
        if bit == '0':
            qml.PauliX(wires=img_wires[i])

### (3) Circuito Principal (QPE Manual)
raw_image = np.array([[0,   120, 0, 0],
                      [254, 128, 254, 50],
                      [0,   254, 0, 10],
                      [100, 254, 120, 99]])

input_phases, n_image_wires = get_image_setup(raw_image)
n_estimation_wires = 8
total_wires = n_estimation_wires + n_image_wires
dev = qml.device('default.qubit', wires=total_wires)

@qml.qnode(dev)
def retrieval_circuit(flat_phases):
    est_wires = list(range(n_estimation_wires))
    img_wires = list(range(n_estimation_wires, total_wires))

    ## (a) Superposición ##
    for w in est_wires:
        qml.Hadamard(wires=w)
    for w in img_wires:
        qml.Hadamard(wires=w)

    qml.Barrier()

    ## (b) Phase kickback con Gray ##
    for i, wire_j in enumerate(reversed(est_wires)):
        power = 2**i
        # Reemplazamos el doble bucle original por una sola llamada al oráculo Gray
        apply_phases_with_gray_code(flat_phases, img_wires, wire_j, power)
        qml.Barrier()

    ## (c) QFT Inversa ##
    qml.adjoint(qml.QFT)(wires=est_wires)

    return qml.probs(wires=range(total_wires))

### MAIN ###
print(f"Procesando imagen de {len(input_phases)} píxeles con {n_image_wires} qubits de posición...")
probs = retrieval_circuit(input_phases)

print("\n--- Análisis de Recuperación de Imagen ---")
for k, p in enumerate(probs):
    if p > 0.001:
        bin_k = format(k, f'0{total_wires}b')
        est_bin = bin_k[:n_estimation_wires]
        img_bin = bin_k[n_estimation_wires:]

        est_int = int(est_bin, 2)
        pixel_idx = int(img_bin, 2)

        if pixel_idx < len(input_phases):
            recovered_intensity = (est_int / (2**n_estimation_wires)) * 255
            print(f"Posición |{img_bin}> (Index {pixel_idx}): "
                  f"Intensidad = {recovered_intensity:.2f} (Prob: {p:.4f})")
### Visualización del circuito ###
fig, ax = qml.draw_mpl(retrieval_circuit)(input_phases)

# Generamos las especificaciones del circuito
circuit_specs = qml.specs(retrieval_circuit)(input_phases)

# Extraemos el objeto de recursos
resources = circuit_specs['resources']

print("---Perfilado del Circuito---")
print(f"Total de operaciones (Compuertas): {resources.num_gates}")
print(f"Profundidad del circuito (Depth): {resources.depth}")

print("\nDesglose de compuertas utilizadas:")
for gate, count in resources.gate_types.items():
    print(f" - {gate}: {count}")

"""## Generalizacion para suma de 2 imagenes (n x m)"""

### I. Oráculo Generalizado ###
def controlled_phase_for_state_power(phi, wires_list, control_values, power):
    #- Aplica la fase (phi * power) al estado especificado dinámicamente.
    # 1. Inversión de bits para seleccionar estado
    for i, bit in enumerate(control_values):
        if bit == 0:
            qml.PauliX(wires=wires_list[i])

    # 2. Fase Controlada Potenciada (Generalizada para n qubits objetivo)
    current_phi = phi * power
    if len(wires_list) == 1:
        qml.PhaseShift(current_phi, wires=wires_list[0])
    else:
        # Controlamos con todos los qubits excepto el último
        controls = wires_list[:-1]
        target = wires_list[-1]
        qml.ctrl(qml.PhaseShift, control=controls)(current_phi, wires=target)

    # 3. Reversión (Uncompute)
    for i, bit in enumerate(control_values):
        if bit == 0:
            qml.PauliX(wires=wires_list[i])

def apply_controlled_image_unitary(image_matrix, target_wires, control_wire, power):
    #- Aplica U^power iterando sobre todos los píxeles de una matriz N x M.
    flat_image = image_matrix.flatten()
    n_qubits = len(target_wires)

    # Genera todas las combinaciones binarias posibles para los qubits objetivo
    binary_states = list(itertools.product([0, 1], repeat=n_qubits))

    def unitary_logic():
        for i, pixel_phase in enumerate(flat_image):
            if pixel_phase > 0: # Optimización: Omitir rotaciones de fase 0
                control_values = binary_states[i]
                controlled_phase_for_state_power(pixel_phase, target_wires, control_values, power)

    # Controlamos toda la operación desde el qubit de estimación
    qml.ctrl(unitary_logic, control=control_wire)()


### II. Configuración y Circuito Dual-Image ###
# Definición de 2 imágenes (ahora generalizadas, ej. 2x4 o de cualquier tamaño)
raw_img1 = np.array([[10,  31, 0,   10],
                     [9,  0,  200, 0]])

raw_img2 = np.array([[25, 54,  87,   6],
                     [10, 20,  54,  1]])

# Cálculo dinámico de qubits necesarios
n_pixels = raw_img1.size
n_image_wires = int(np.ceil(np.log2(n_pixels)))
n_estimation_wires = 8 # Escala de grises (0 a 255?)
total_wires = n_estimation_wires + n_image_wires

dev = qml.device('default.qubit', wires=total_wires)

@qml.qnode(dev)
def dual_phase_encoding_circuit(image_matrix_1, image_matrix_2):
    est_wires = list(range(n_estimation_wires))
    tgt_wires = list(range(n_estimation_wires, total_wires))

    # PASO A: Superposición Total
    for w in est_wires + tgt_wires:
        qml.Hadamard(wires=w)

    # PASO B: Acumulación de Fases
    for i, est_wire in enumerate(reversed(est_wires)):
        power = 2**i
        apply_controlled_image_unitary(image_matrix_1, tgt_wires, est_wire, power)
        apply_controlled_image_unitary(image_matrix_2, tgt_wires, est_wire, power)

    # PASO C: Recuperación
    qml.adjoint(qml.QFT)(wires=est_wires)

    return qml.probs(wires=est_wires + tgt_wires)

### MAIN ###
phases_1 = (raw_img1 / 255.0) * (2 * np.pi)
phases_2 = (raw_img2 / 255.0) * (2 * np.pi)

print(f"Ejecutando QPE para imágenes de {raw_img1.shape}...")
probs = dual_phase_encoding_circuit(phases_1, phases_2)

## Análisis de Resultados Generalizado ##
def analyze_results(probabilities, image_shape, threshold=0.05):
    print(f"\n{'Posición (Bin)':<15} {'Suma Esperada':<15} {'Valor Recuperado':<15} {'Probabilidad'}")
    print("-" * 65)

    for k, p in enumerate(probabilities):
        if p > threshold:
            bin_k = format(k, f'0{total_wires}b')
            est_bin = bin_k[:n_estimation_wires]
            img_bin = bin_k[n_estimation_wires:]

            est_int = int(est_bin, 2)
            pixel_idx = int(img_bin, 2)

            # Evitar índices fuera de rango si n_pixels no es potencia de 2
            if pixel_idx >= np.prod(image_shape):
                continue

            row, col = np.unravel_index(pixel_idx, image_shape)
            val1 = raw_img1[row, col]
            val2 = raw_img2[row, col]
            expected_sum = val1 + val2

            recovered_val = (est_int / (2**n_estimation_wires)) * 255
            print(f"|{img_bin}> ({row},{col})    {val1}+{val2}={expected_sum:<7} {recovered_val:.2f}           {p:.4f}")

analyze_results(probs, raw_img1.shape)
fig, ax = qml.draw_mpl(dual_phase_encoding_circuit)(phases_1, phases_2)

### Perfilado de Recursos (Métricas Reales)
circuit_specs = qml.specs(dual_phase_encoding_circuit)(phases_1, phases_2)
resources = circuit_specs['resources']

print("\n=== Perfilado del Circuito ===")
print(f"Total de operaciones brutas: {resources.num_gates}")
print(f"Profundidad del circuito (Depth): {resources.depth}")
print("\nDesglose de compuertas utilizadas:")
for gate, count in resources.gate_types.items():
    print(f" - {gate}: {count}")

"""## Generalización codificacion 1 imagen (n x m)"""

# ==========================================
# 1. Configuración y Preprocesamiento
# ==========================================

def get_image_setup(raw_img_array):
    """
    Calcula los parámetros necesarios para una imagen de tamaño arbitrario.
    """
    flat_image = raw_img_array.flatten()
    n_pixels = len(flat_image)

    # Calculamos qubits necesarios: log2 redondeado hacia arriba
    n_image_wires = int(np.ceil(np.log2(n_pixels)))

    # Normalización a fases [0, 2pi]
    phases = (flat_image / 255.0) * (2 * np.pi)

    return phases, n_image_wires

# Inicialización del dispositivo
dev = qml.device('default.qubit', wires=total_wires)

# ==========================================
# 2. Definición del Oráculo Generalizado
# ==========================================

def apply_controlled_phase_at_index(phase, index, img_wires, est_wire, power):
    """
    Aplica una fase controlada asegurando que el qubit de estimación sea
    explícitamente un control de la operación, evitando colisiones topológicas.
    """
    binary_rep = format(index, f'0{len(img_wires)}b')

    # 1. Aplicar Anti-Controles (PauliX)
    # Convertimos el estado del índice buscado temporalmente a |11...1>
    for i, bit in enumerate(binary_rep):
        if bit == '0':
            qml.PauliX(wires=img_wires[i])

    # 2. Reestructuración de Jerarquía y Topología
    current_phi = phase * power

    # Separamos un qubit de imagen para que sea el objetivo exclusivo
    target_wire = img_wires[-1]

    # El cable de estimación es el control principal, apoyado por el resto de la imagen
    control_wires = [est_wire] + list(img_wires[:-1])

    # Aplicamos la fase controlada.
    # Al estar el target_wire garantizado en |1>, PhaseShift aplicará e^{i*phi}
    qml.ctrl(qml.PhaseShift, control=control_wires)(current_phi, wires=target_wire)

    # 3. Revertir Anti-Controles (Uncompute)
    for i, bit in enumerate(binary_rep):
        if bit == '0':
            qml.PauliX(wires=img_wires[i])

# ==========================================
# 3. Circuito Principal (QPE Manual)
# ==========================================

@qml.qnode(dev)
def retrieval_circuit(flat_phases):

    est_wires = list(range(n_estimation_wires))
    img_wires = list(range(n_estimation_wires, total_wires))

    # --- PASO A: Superposición (Hadamards) ---
    for w in est_wires:
        qml.Hadamard(wires=w)
    for w in img_wires:
        qml.Hadamard(wires=w)

    # --- PASO B: Retroceso de Fase (Phase Kickback) ---
    for i, wire_j in enumerate(reversed(est_wires)):
        power = 2**i

        for idx, phi in enumerate(flat_phases):
            if abs(phi) > 1e-5:
                apply_controlled_phase_at_index(phi, idx, img_wires, wire_j, power)

    # --- PASO C: Transformada Cuántica de Fourier Inversa ---
    qml.adjoint(qml.QFT)(wires=est_wires)

    return qml.probs(wires=range(total_wires))

### MAIN ###

# Definimos una imagen arbitraria (Ejemplo: 4x4 píxeles)
# Puedes cambiar esta matriz por cualquier tamaño.
raw_image = np.array([
    [0,  120, 0, 0],
    [254, 128, 254, 50],
    [0,  254, 0, 10],
    [100,  254, 120, 99]
])

input_phases, n_image_wires = get_image_setup(raw_image)
n_estimation_wires = 8 # Precisión de 8 bits
total_wires = n_estimation_wires + n_image_wires

print(f"Procesando imagen de {len(input_phases)} píxeles con {n_image_wires} qubits de posición...")
probs = retrieval_circuit(input_phases)

print("\n--- Análisis de Recuperación de Imagen ---")

# Filtramos las probabilidades. El sistema tiene 2^(n_est + n_img) estados posibles
for k, p in enumerate(probs):
    if p > 0.001: # Umbral de ruido numérico
        # Convertimos el índice k a binario
        # Formato: [Estimación (n_est bits)] [Imagen (n_img bits)]
        total_bits = n_estimation_wires + n_image_wires
        bin_k = format(k, f'0{total_bits}b')

        # Separamos los registros dinámicamente
        est_bin = bin_k[:n_estimation_wires]  # Bits de fase
        img_bin = bin_k[n_estimation_wires:]  # Bits de posición

        # Convertimos a valores decimales
        est_int = int(est_bin, 2)
        pixel_idx = int(img_bin, 2)

        # Validación: Solo imprimimos índices que existen en la imagen original
        # (El padding de qubits puede generar índices vacíos fantasmas si P < 2^n)
        if pixel_idx < len(input_phases):
             # Revertir normalización
            recovered_intensity = (est_int / (2**n_estimation_wires)) * 255

            print(f"Posición |{img_bin}> (Index {pixel_idx}): "
                  f"Intensidad Recuperada = {recovered_intensity:.2f} "
                  f"(Prob: {p:.4f})")

## Visualizacion ##
# Nota: Dibujar un circuito con bucles grandes puede ser pesado visualmente.
print("\nGenerando diagrama del circuito...")
fig, ax = qml.draw_mpl(retrieval_circuit)(input_phases)
plt.show()

# Generamos las especificaciones del circuito
circuit_specs = qml.specs(retrieval_circuit)(input_phases)

# Extraemos el objeto de recursos
resources = circuit_specs['resources']

print("---Perfilado del Circuito---")
print(f"Total de operaciones (Compuertas): {resources.num_gates}")
print(f"Profundidad del circuito (Depth): {resources.depth}")

print("\nDesglose de compuertas utilizadas:")
for gate, count in resources.gate_types.items():
    print(f" - {gate}: {count}")

# ==========================================
# Post-Procesamiento: Cálculo del Valor Esperado
# ==========================================

print("Iniciando agregación de estados dispersos (Spectral Leakage Correction)...")

# Diccionario para almacenar acumulados por píxel
# Estructura: { pixel_idx: {'weighted_sum': float, 'total_prob': float} }
pixel_reconstruction = {}

# Parámetros del sistema (asegúrate de que estas variables existan en tu entorno)
total_bits = n_estimation_wires + n_image_wires

# 1. Barrido de la distribución de probabilidad
for k, p in enumerate(probs):
    # Usamos un umbral muy bajo para capturar las "colas" de la dispersión
    # y hacer el promedio más preciso.
    if p > 0.0001:

        # Decodificación del estado k
        bin_k = format(k, f'0{total_bits}b')
        est_bin = bin_k[:n_estimation_wires]
        img_bin = bin_k[n_estimation_wires:]

        # Conversión a enteros
        pixel_idx = int(img_bin, 2)
        est_int = int(est_bin, 2)

        # Validar que el píxel existe en la imagen original
        # (Ignorar estados fantasma por padding de qubits)
        if pixel_idx < len(input_phases):

            # Recuperar intensidad cruda (0-255) para este estado k
            intensity_val = (est_int / (2**n_estimation_wires)) * 255

            # Inicializar entrada en el diccionario si es nueva
            if pixel_idx not in pixel_reconstruction:
                pixel_reconstruction[pixel_idx] = {'weighted_sum': 0.0, 'total_prob': 0.0}

            # Acumular para el promedio ponderado
            # Numerador: Suma de (Valor * Probabilidad)
            pixel_reconstruction[pixel_idx]['weighted_sum'] += intensity_val * p
            # Denominador: Suma de Probabilidades (para normalizar)
            pixel_reconstruction[pixel_idx]['total_prob'] += p

# 2. Cálculo de promedios y visualización final
print("\n--- Imagen Reconstruida (Promedio Ponderado) ---")
print(f"{'Index':<8} | {'Binario':<8} | {'Intensidad Real':<18} | {'Probabilidad Total':<15}")
print("-" * 60)

sorted_indices = sorted(pixel_reconstruction.keys())

for idx in sorted_indices:
    data = pixel_reconstruction[idx]

    # Aplicación de la fórmula del Valor Esperado <I>
    expected_intensity = data['weighted_sum'] / data['total_prob']

    # Formato binario para referencia visual
    idx_bin = format(idx, f'0{n_image_wires}b')

    print(f"{idx:<8} | {idx_bin:<8} | {expected_intensity:<18.2f} | {data['total_prob']:<15.4f}")

    # Validación Opcional: Comparar con original si está disponible
    # original_val = raw_image.flatten()[idx]
    # error = abs(original_val - expected_intensity)
    # print(f"   -> Error respecto original: {error:.2f}")

"""# Modelos previos e ideas

## Metodo (1) suma para 2 imagenes (2x2 pixeles)

En este metodo usamos el phase-kickback para cada imagen codificada, es decir, que el registro de estimacion contiene la información de ambas imagenes y ahi se realiza el proceso de suma de fases.
"""

# --- 1. Definición del Oráculo (Misma lógica, reutilizable) ---
def controlled_phase_for_state_power(phi, wires_list, control_values, power):
    """ Aplica la fase (phi * power) al estado especificado. """
    w0, w1 = wires_list[0], wires_list[1]

    # 1. Inversión de bits para seleccionar estado
    for i in range(len(control_values)):
        if control_values[i] == 0:
            qml.PauliX(wires=wires_list[i])

    # 2. Fase Controlada Potenciada
    current_phi = phi * power
    qml.ControlledPhaseShift(current_phi, wires=[w0, w1])

    # 3. Reversión (Uncompute)
    for i in range(len(control_values)):
        if control_values[i] == 0:
            qml.PauliX(wires=wires_list[i])

def apply_controlled_image_unitary(image_matrix, target_wires, control_wire, power):
    """ Aplica U^power de una matriz de imagen dada. """
    def unitary_logic():
        controlled_phase_for_state_power(image_matrix[0][0], target_wires, [0, 0], power)
        controlled_phase_for_state_power(image_matrix[0][1], target_wires, [0, 1], power)
        controlled_phase_for_state_power(image_matrix[1][0], target_wires, [1, 0], power)
        controlled_phase_for_state_power(image_matrix[1][1], target_wires, [1, 1], power)

    qml.ctrl(unitary_logic, control=control_wire)()


# --- 2. Circuito Dual-Image ---
n_image_wires = 2
n_estimation_wires = 8
dev = qml.device('default.qubit', wires=n_image_wires + n_estimation_wires)

@qml.qnode(dev)
def dual_phase_encoding_circuit(image_matrix_1, image_matrix_2):
    est_wires = list(range(n_estimation_wires))
    tgt_wires = list(range(n_estimation_wires, n_estimation_wires + n_image_wires))

    # PASO A: Superposición Total
    for w in est_wires:
        qml.Hadamard(wires=w)
    for w in tgt_wires:
        qml.Hadamard(wires=w)

    # PASO B: Acumulación de Fases (Imagen 1 + Imagen 2)
    # Iteramos sobre los cables de estimación
    for i, est_wire in enumerate(reversed(est_wires)):
        power = 2**i

        # 1. Inyectar Fase de la Imagen 1
        apply_controlled_image_unitary(image_matrix_1, tgt_wires, est_wire, power)

        # 2. Inyectar Fase de la Imagen 2 (ACUMULACIÓN)
        # Al aplicar esto secuencialmente antes de la QFT inversa,
        # las fases se suman matemáticamente: e^(i*phi1) * e^(i*phi2) = e^(i*(phi1+phi2))
        apply_controlled_image_unitary(image_matrix_2, tgt_wires, est_wire, power)

        qml.Barrier() # Para visualizar separación de pasos de potencia

    # PASO C: Recuperación (QFT Inversa)
    # Se realiza UNA sola vez al final para decodificar la fase total acumulada
    qml.adjoint(qml.QFT)(wires=est_wires)

    return qml.probs(wires=est_wires + tgt_wires)

### MAIN ###

# Definición de 2 imágenes sencillas (2x2)
# Imagen 1: Fondo oscuro con un punto gris
raw_img1 = np.array([[0, 50],
                     [0, 0]])

# Imagen 2: Fondo oscuro con un punto gris en LA MISMA posición (para probar suma)
# y otro en otra posición.
raw_img2 = np.array([[25, 55],
                     [123, 211]])

# Normalización a fases (0 a 2pi)
phases_1 = (raw_img1 / 255.0) * (2 * np.pi)
phases_2 = (raw_img2 / 255.0) * (2 * np.pi)

print("Ejecutando QPE con Acumulación de 2 Imágenes...")
probs = dual_phase_encoding_circuit(phases_1, phases_2)

print("\n--- Análisis de Resultados ---")

# Función auxiliar para decodificar
def analyze_results(probabilities, threshold=0.05):
    print(f"{'Posición (Bin)':<15} {'Suma Esperada':<15} {'Valor Recuperado':<15} {'Probabilidad'}")
    print("-" * 65)

    for k, p in enumerate(probabilities):
        if p > threshold:
            # Decodificación de binarios
            total_bits = n_estimation_wires + n_image_wires
            bin_k = format(k, f'0{total_bits}b')
            est_bin = bin_k[:n_estimation_wires]
            img_bin = bin_k[n_estimation_wires:]

            est_int = int(est_bin, 2)
            pixel_idx = int(img_bin, 2)

            # Cálculo de coordenadas para mostrar qué sumamos
            row, col = divmod(pixel_idx, 2)
            val1 = raw_img1[row][col]
            val2 = raw_img2[row][col]
            expected_sum = val1 + val2

            # Recuperación
            # Nota: Si la suma supera 255, en QPE esto es módulo 2pi.
            # Aquí, como 2pi = 255 (en nuestra escala), se comportará como overflow de 8 bits.
            recovered_val = (est_int / (2**n_estimation_wires)) * 255

            print(f"|{img_bin}> ({row},{col})    {val1}+{val2}={expected_sum:<7} {recovered_val:.2f}           {p:.4f}")

analyze_results(probs)
fig, ax = qml.draw_mpl(dual_phase_encoding_circuit)(phases_1, phases_2)

"""## Metodo (2) para 2 imagenes (2x2 pixeles) NO FUNCIONA JAJA

En este metodo solo usamos una etapa de phase-kickback para regresar la informacion de ambas imagenes para poder ser recuperada la suma de fases (pixeles) de las imagenes.
"""

# --- 1. Lógica Imagen 1: Codificación Local ---
def encode_phase_on_target(phi, wires, state):
    """ Aplica la fase phi a un estado base específico de los cables dados. """
    # X gates para seleccionar el estado
    for i, s in enumerate(state):
        if s == 0:
            qml.PauliX(wires=wires[i])
    qml.Barrier()
    # Al aplicar PhaseShift a uno de los cables cuando está en |1>,
    # la fase se añade a todo el estado (rama de la superposición).
    qml.PhaseShift(phi, wires=wires[0])
    qml.Barrier()
    # Reversión
    for i, s in enumerate(state):
        if s == 0:
            qml.PauliX(wires=wires[i])
def encode_image_locally(image_matrix, tgt_wires):
    """ Codifica la matriz de imagen SOLO en los cables de imagen. """
    encode_phase_on_target(image_matrix[0][0], tgt_wires, [0, 0])
    encode_phase_on_target(image_matrix[0][1], tgt_wires, [0, 1])
    encode_phase_on_target(image_matrix[1][0], tgt_wires, [1, 0])
    encode_phase_on_target(image_matrix[1][1], tgt_wires, [1, 1])


# --- 2. Lógica Imagen 2: QPE Estándar (Phase Kickback) ---
def controlled_phase_for_state_power(phi, wires_list, control_values, power):
    w0, w1 = wires_list[0], wires_list[1]
    for i in range(len(control_values)):
        if control_values[i] == 0:
            qml.PauliX(wires=wires_list[i])

    qml.ControlledPhaseShift(phi * power, wires=[w0, w1])

    for i in range(len(control_values)):
        if control_values[i] == 0:
            qml.PauliX(wires=wires_list[i])

def apply_controlled_image_unitary(image_matrix, target_wires, control_wire, power):
    def unitary_logic():
        controlled_phase_for_state_power(image_matrix[0][0], target_wires, [0, 0], power)
        controlled_phase_for_state_power(image_matrix[0][1], target_wires, [0, 1], power)
        controlled_phase_for_state_power(image_matrix[1][0], target_wires, [1, 0], power)
        controlled_phase_for_state_power(image_matrix[1][1], target_wires, [1, 1], power)

    qml.ctrl(unitary_logic, control=control_wire)()


# --- 3. Circuito de Prueba de Hipótesis ---
n_image_wires = 2
n_estimation_wires = 8
dev = qml.device('default.qubit', wires=n_image_wires + n_estimation_wires)

@qml.qnode(dev)
def hypothesis_testing_circuit(image_matrix_1, image_matrix_2):
    est_wires = list(range(n_estimation_wires))
    tgt_wires = list(range(n_estimation_wires, n_estimation_wires + n_image_wires))

    # PASO A: Superposición
    for w in est_wires:
        qml.Hadamard(wires=w)
    for w in tgt_wires:
        qml.Hadamard(wires=w)

    qml.Barrier()

    # PASO B1: Hipótesis (Imagen 1 codificada SOLO en registro de imagen)
    encode_image_locally(image_matrix_1, tgt_wires)

    qml.Barrier()

    # PASO B2: QPE Estándar (Imagen 2)
    for i, est_wire in enumerate(reversed(est_wires)):
        power = 2**i
        apply_controlled_image_unitary(image_matrix_2, tgt_wires, est_wire, power)

    qml.Barrier()

    # PASO C: QFT Inversa
    qml.adjoint(qml.QFT)(wires=est_wires)

    return qml.probs(wires=est_wires + tgt_wires)

### MAIN - Demostración ###
# Definimos valores claros y muy distintos para que la prueba no deje lugar a dudas
raw_img1 = np.array([[100, 100], [100, 100]]) # Imagen 1: Todo en 100
raw_img2 = np.array([[50, 50], [50, 50]])     # Imagen 2: Todo en 50

phases_1 = (raw_img1 / 255.0) * (2 * np.pi)
phases_2 = (raw_img2 / 255.0) * (2 * np.pi)

print("Ejecutando Prueba de Hipótesis...\n")
probs = hypothesis_testing_circuit(phases_1, phases_2)

print(f"{'Posición':<10} {'Valor Img 1':<15} {'Valor Img 2':<15} {'Valor Recuperado':<15}")
print("-" * 55)

for k, p in enumerate(probs):
    if p > 0.05:
        total_bits = n_estimation_wires + n_image_wires
        bin_k = format(k, f'0{total_bits}b')
        est_bin = bin_k[:n_estimation_wires]
        img_bin = bin_k[n_estimation_wires:]

        est_int = int(est_bin, 2)
        pixel_idx = int(img_bin, 2)
        row, col = divmod(pixel_idx, 2)

        recovered_val = (est_int / (2**n_estimation_wires)) * 255

        val_img1 = raw_img1[row][col]
        val_img2 = raw_img2[row][col]

        print(f"({row},{col})       {val_img1:<15} {val_img2:<15} {recovered_val:.2f}")

print("\nConclusión de la ejecución: El valor recuperado corresponde ÚNICAMENTE a la Imagen 2.")

# Visualización opcional
fig, ax = qml.draw_mpl(hypothesis_testing_circuit)(phases_1, phases_2)

"""## Metodo usando estimación de fase"""

# --- 1. Definición del Oráculo (Lógica de Imagen) ---
def controlled_phase_for_state_power(phi, wires_list, control_values, power):
    """
    Aplica la fase (phi * power) al estado especificado.
    Esto simula aplicar el operador unitario U, 'power' veces consecutivas.
    U^k |psi> = e^(i * k * phi) |psi>
    """
    # Identificar cables
    w0, w1 = wires_list[0], wires_list[1]

    # 1. Inversión de bits (X gates) para seleccionar el estado correcto
    for i in range(len(control_values)):
        if control_values[i] == 0:
            qml.PauliX(wires=wires_list[i])

    # 2. Fase Controlada "Potenciada"
    # En lugar de aplicar U repetidamente, multiplicamos el ángulo.
    # U^power equivale a rotar (phi * power).
    current_phi = phi * power
    qml.ControlledPhaseShift(current_phi, wires=[w0, w1])

    # 3. Reversión (Uncompute)
    for i in range(len(control_values)):
        if control_values[i] == 0:
            qml.PauliX(wires=wires_list[i])

def apply_controlled_image_unitary(image_matrix, target_wires, control_wire, power):
    """
    Aplica una versión controlada del operador de imagen elevado a una potencia.
    Control: 'control_wire'
    Operación: U^power sobre 'target_wires'
    """
    # Como controlled_phase_for_state ya usa ControlledPhaseShift,
    # necesitamos añadir un control extra.
    # En PennyLane, podemos usar qml.ctrl para añadir control a una función arbitraria.

    def unitary_logic():
        # Lógica para los 4 píxeles (00, 01, 10, 11)
        controlled_phase_for_state_power(image_matrix[0][0], target_wires, [0, 0], power)
        controlled_phase_for_state_power(image_matrix[0][1], target_wires, [0, 1], power)
        controlled_phase_for_state_power(image_matrix[1][0], target_wires, [1, 0], power)
        controlled_phase_for_state_power(image_matrix[1][1], target_wires, [1, 1], power)

    # Aplicamos la lógica condicionada al cable de estimación actual
    qml.ctrl(unitary_logic, control=control_wire)()


# --- 2. Circuito Desglosado ---
n_image_wires = 2
n_estimation_wires = 8
dev = qml.device('default.qubit', wires=n_image_wires + n_estimation_wires)

@qml.qnode(dev)
def phase_encoding_circuit(image_matrix):
    est_wires = list(range(n_estimation_wires))
    tgt_wires = list(range(n_estimation_wires, n_estimation_wires + n_image_wires))

    # PASO A: Superposición
    # Ponemos los qubits de estimación en |+> para interferometría
    for w in est_wires:
        qml.Hadamard(wires=w)

    # Ponemos los qubits de imagen (target) en superposición para procesar todos los píxeles
    for w in tgt_wires:
        qml.Hadamard(wires=w)

    # PASO B: Aplicación de Unitarios Controlados (Phase Kickback)
    # Iteramos sobre los cables de estimación desde el LSB (menos significativo) hacia arriba.
    # En QPE estándar, el wire j controla U^(2^j).
    # PennyLane ordena los wires de estimación tal que wires[n-1] es el bit de menor peso para la fase.

    for i, est_wire in enumerate(reversed(est_wires)):
        # i será 0, 1, 2... correspondiente a la potencia 2^0, 2^1...
        power = 2**i

        # Aplicamos C-U^(power)
        # Esto inyecta la fase relativa en el qubit 'est_wire'
        apply_controlled_image_unitary(image_matrix, tgt_wires, est_wire, power)
        qml.Barrier()

    # PASO C: Transformada Cuántica de Fourier Inversa (QFT_dagger)
    # Convierte la información codificada en fase a la base computacional (bits)
    qml.adjoint(qml.QFT)(wires=est_wires)

    return qml.probs(wires=est_wires + tgt_wires)

### MAIN ###
raw_image = np.array([[0, 10], [128, 164]])
input_phases = (raw_image / 255.0) * (2 * np.pi)

print("Ejecutando QPE Manual paso a paso...")
probs = phase_encoding_circuit(input_phases)

print("\nVerificación de un resultado (Ej: Píxel 1,0 - Valor 128):")
# Buscamos en la distribución el estado correspondiente a píxel 10 (binario) e intensidad ~0.5
# Indexado manual para verificar:
# Estructura del bitstring: [8 bits estimación] [2 bits imagen]
# Esperamos: Intensidad 128 -> fase pi -> binario 10000000 (en estimación)
# Posición 1,0 -> binario 10 (en imagen)
# Estado total esperado: |10000000> |10>  ->  |1000000010>

# Filtramos las probabilidades. El sistema tiene 2^(8+2) = 1024 estados.
# Buscamos estados con probabilidad > 0 (idealmente 0.25 para cada uno de los 4 píxeles)
for k, p in enumerate(probs):
    if p > 0.1: # Umbral de ruido numérico
        # Convertimos el índice k a binario
        # Formato: [Estimación (8 bits)] [Imagen (2 bits)]
        total_bits = n_estimation_wires + n_image_wires
        bin_k = format(k, f'0{total_bits}b')

        # Separamos los registros
        est_bin = bin_k[:n_estimation_wires]  # Bits de fase (valor del píxel)
        img_bin = bin_k[n_estimation_wires:]  # Bits de posición (coordenada)

        # Convertimos a valores decimales
        # La fase recuperada phi_est = valor_entero / 2^8 * 2pi
        est_int = int(est_bin, 2)
        pixel_idx = int(img_bin, 2)

        # Revertir normalización para obtener intensidad 0-255
        # intensidad = (est_int / 2^8) * 255
        recovered_intensity = (est_int / (2**n_estimation_wires)) * 255

        print(f"Posición |{img_bin}> (Index {pixel_idx}): "
              f"Intensidad Recuperada = {recovered_intensity:.2f} "
              f"(Prob: {p:.4f})")

fig, ax = qml.draw_mpl(phase_encoding_circuit)(input_phases)

"""# Tests

## Generalizacion con phase invertida a estimacion
"""

# ==========================================
# 1. Configuración y Preprocesamiento
# ==========================================

def get_image_setup(raw_img_array):
    """
    Calcula los parámetros necesarios para una imagen de tamaño arbitrario.
    """
    flat_image = raw_img_array.flatten()
    n_pixels = len(flat_image)

    # Calculamos qubits necesarios: log2 redondeado hacia arriba
    # Ejemplo: 9 píxeles -> necesitan 4 qubits (16 estados)
    n_image_wires = int(np.ceil(np.log2(n_pixels)))

    # Normalización a fases [0, 2pi]
    phases = (flat_image / 255.0) * (2 * np.pi)

    return phases, n_image_wires

# Inicialización del dispositivo
dev = qml.device('default.qubit', wires=total_wires)

# ==========================================
# 2. Definición del Oráculo Generalizado
# ==========================================

def apply_controlled_phase_at_index(phase, index, img_wires, est_wire, power):
    """
    Aplica una fase controlada específica a un estado base (índice del píxel).

    Args:
        phase (float): Valor del píxel (ángulo).
        index (int): Índice posicional del píxel (0, 1, 2...).
        img_wires (list): Cables que codifican la posición.
        est_wire (int): Cable de estimación actual (control principal).
        power (int): Potencia del operador unitario (2^j).
    """
    # Convertimos el índice a binario para saber qué qubits negar (flip)
    # Ejemplo: si n_img=3 y index=1 ('001'), debemos aplicar X a los dos primeros
    # para convertir el estado |001> en |111> y activar el control.
    binary_rep = format(index, f'0{len(img_wires)}b')

    # 1. Aplicar Anti-Controles (PauliX) donde el bit es '0'
    for i, bit in enumerate(binary_rep):
        if bit == '0':
            qml.PauliX(wires=img_wires[i])

    # 2. Aplicar Fase Multicontrolada
    # La fase efectiva es (phase * power).
    # Usamos est_wire como objetivo de la fase y img_wires como controles.
    # Nota: Matemáticamente, la fase es global al subespacio, el target es indistinto
    # entre los controles siempre que todos sean 1.
    current_phi = phase * power

    # qml.ctrl permite generalizar el control a N cables sin usar templates complejos
    qml.ctrl(qml.PhaseShift, control=est_wires)(current_phi, wires=est_wire)
    # qml.ctrl(qml.PhaseShift, control=[est_wire] + list(img_wires))(current_phi, wires=img_wires[-1])

    # 3. Revertir Anti-Controles (Uncompute)
    for i, bit in enumerate(binary_rep):
        if bit == '0':
            qml.PauliX(wires=img_wires[i])

# ==========================================
# 3. Circuito Principal (QPE Manual)
# ==========================================

@qml.qnode(dev)
def retrieval_circuit(flat_phases):

    # Definición de rangos de cables
    est_wires = list(range(n_estimation_wires))
    img_wires = list(range(n_estimation_wires, total_wires))

    # --- PASO A: Superposición (Hadamards) ---
    # Inicializamos todos los cables en |+>
    for w in est_wires:
        qml.Hadamard(wires=w)
    for w in img_wires:
        qml.Hadamard(wires=w)

    # --- PASO B: Retroceso de Fase (Phase Kickback) ---
    # Iteramos sobre los cables de estimación (bits de precisión)
    for i, wire_j in enumerate(reversed(est_wires)):
        power = 2**i # Potencia del operador U^(2^i)

        # Iteramos sobre CADA píxel de la imagen
        # Esto construye el operador diagonal U completo
        for idx, phi in enumerate(flat_phases):
            # Solo aplicamos lógica si la fase es significativa (optimización opcional)
            if abs(phi) > 1e-5:
                apply_controlled_phase_at_index(phi, idx, img_wires, wire_j, power)

    # --- PASO C: Transformada Cuántica de Fourier Inversa ---
    # Única función "complex" permitida por requerimiento
    qml.adjoint(qml.QFT)(wires=est_wires)

    return qml.probs(wires=range(total_wires))

"""### Simplified Phase Encoding Function

This section introduces a simplified version of your `my_quantum_function` called `simplified_quantum_function`. The original function used a relatively complex sequence of gates to apply a phase shift to each specific basis state (e.g., $|00\rangle$, $|01\rangle$, etc.).

The simplification is achieved by using a helper function `controlled_phase_for_state`. This helper function effectively applies a global phase to a target computational basis state using `qml.PauliX` gates to 'mark' the desired state (by flipping the '0' controls to '1') and then applying a `qml.ControlledPhaseShift` (which acts on the $|11\rangle$ state for two qubits). Finally, the `qml.PauliX` gates are applied again to 'unmark' the state. This method significantly reduces the number of gates required for each conditional phase application.
"""

def controlled_phase_for_state(phi, wires_list, control_values):
    """
    Applies a global phase phi to the state specified by control_values.
    Assumes a 2-qubit system and uses qml.ControlledPhaseShift which acts on |11>.
    """
    if len(wires_list) != len(control_values) or len(wires_list) != 2:
        raise ValueError("This helper is designed for 2-qubit systems.")

    # Flip control wires that need to be '0' to '1'
    for i in range(len(control_values)):
        if control_values[i] == 0:
            qml.PauliX(wires=wires_list[i])

    # Apply the controlled phase. qml.ControlledPhaseShift acts on |11> state.
    # It applies exp(i*phi) to the |11> component of the wires it acts on.
    qml.ControlledPhaseShift(phi, wires=[wires_list[0], wires_list[1]])

    # Flip back the control wires
    for i in range(len(control_values)):
        if control_values[i] == 0:
            qml.PauliX(wires=wires_list[i])

dev = qml.device('default.qubit', wires=2)
@qml.qnode(dev)
def simplified_quantum_function(test_image):
    # Initialize in superposition
    qml.H(wires=[0])
    qml.H(wires=1)
    qml.Barrier()

    # Apply phase encoding for each basis state
    # For |00> state, apply phase test_image[0][0]
    controlled_phase_for_state(test_image[0][0], [0, 1], [0, 0])
    qml.Barrier()

    # For |01> state, apply phase test_image[0][1]
    controlled_phase_for_state(test_image[0][1], [0, 1], [0, 1])
    qml.Barrier()

    # For |10> state, apply phase test_image[1][0]
    controlled_phase_for_state(test_image[1][0], [0, 1], [1, 0])
    qml.Barrier()

    # For |11> state, apply phase test_image[1][1]
    controlled_phase_for_state(test_image[1][1], [0, 1], [1, 1])
    qml.Barrier()

    # # Inverse Quantum Fourier Transform (iQFT) part (copied from your original code)
    # wires = range(2)
    # n = len(wires)
    # for i in range(n // 2):
    #     qml.SWAP(wires=[wires[i], wires[n - 1 - i]])

    # for j in range(n):
    #     for k in range(j + 1, n):
    #         angle = -np.pi / (2 ** (k - j))
    #         qml.ControlledPhaseShift(angle, wires=[wires[k], wires[j]])
    #     qml.Hadamard(wires=wires[j])

    return qml.state(), qml.probs(wires=[0,1])

print(qml.draw_mpl(simplified_quantum_function)(test_image_encoded))

import matplotlib.pyplot as plt

# Assuming test_image_encoded is already defined from previous cells
results_simplified, probs_simplified = simplified_quantum_function(test_image_encoded)

# Extract the real part of the state vector from the simplified function
state_real_part_simplified = results_simplified.real

# Create a bar plot for the simplified function's output
plt.figure(figsize=(8, 5))
plt.bar(range(len(state_real_part_simplified)), state_real_part_simplified)
plt.xlabel("|x⟩")
plt.xticks(range(len(state_real_part_simplified)))
plt.ylabel("Amplitude (real part)")
plt.title("Real Part of Quantum State Amplitudes from simplified_quantum_function")
plt.show()

print("State vector from simplified function:", results_simplified)
print("Probabilities from simplified function:", probs_simplified)

"""### Encoding Circuit Visualization

This circuit prepares the image qubits in a superposition and then applies the `encoding_unitary`, which embeds the pixel values as phases.
"""

# Define a device specifically for the encoding part (image wires only)
dev_encoding = qml.device("default.qubit", wires=n_image_wires)

@qml.qnode(dev_encoding)
def encoding_circuit_display():
    # Prepare image_wires in superposition
    for i in range(n_image_wires):
        qml.Hadamard(wires=i)

    # Apply the encoding unitary (defined globally from pixel_data)
    # This operation implicitly acts on the wires specified during its creation (image_wires)
    # Apply phase encoding for each basis state
    # For |00> state, apply phase test_image[0][0]
    controlled_phase_for_state(test_image[0][0], [0, 1], [0, 0])
    qml.Barrier()

    # For |01> state, apply phase test_image[0][1]
    controlled_phase_for_state(test_image[0][1], [0, 1], [0, 1])
    qml.Barrier()

    # For |10> state, apply phase test_image[1][0]
    controlled_phase_for_state(test_image[1][0], [0, 1], [1, 0])
    qml.Barrier()

    # For |11> state, apply phase test_image[1][1]
    controlled_phase_for_state(test_image[1][1], [0, 1], [1, 1])
    qml.Barrier()

    return qml.state()

print("Encoding Circuit:")
fig, ax = qml.draw_mpl(encoding_circuit_display)()
plt.show()

"""### Complete Circuit Visualization (Encoding + Retrieval)

This is the full `retrieval_circuit` which includes the initial superposition on image qubits and the Quantum Phase Estimation (QPE) using the `encoding_unitary` to retrieve the pixel values.
"""

import matplotlib.pyplot as plt

print("Complete Retrieval Circuit (QPE):")
fig, ax = qml.draw_mpl(retrieval_circuit)()
#plt.show()

def bitwise_dot_product(a,b):
  res_dot = 0
  for i in range(len(a)):
    res_dot += int(a[i])*int(b[i])
  res_dot = res_dot % 2
  return res_dot

dev = qml.device('default.qubit', wires=2)
@qml.qnode(dev)
def my_quantum_function(test_image):
    # qml.H(wires=[0])
    # qml.H(wires=1)
    # qml.Barrier()
    ####################################
    ### ORACULO PARA CODIFICAR |00> ###
    # qml.X(wires=0) # Marcado
    # qml.X(wires=1)
    # qml.H(wires=[1])
    # qml.CNOT(wires=[0,1])
    # qml.PhaseShift(test_image[0][0], wires=0)
    # qml.H(wires=[1])
    # ### CORRECCION DE FASE ###
    # qml.X(wires=1)
    # qml.ControlledPhaseShift(-test_image[0][0], wires=[0,1])
    # qml.X(wires=1)
    # ##########################
    # qml.X(wires=[0]) # Desmarcado
    # qml.X(wires=[1])
    # qml.Barrier()
    ####################################
    ### ORACULO PARA CODIFICAR |01> ###
    qml.X(wires=[0]) # Marcado
    qml.Barrier()
    qml.H(wires=[1])
    qml.CNOT(wires=[0,1])
    qml.H(wires=[1])
    qml.Barrier()
    qml.PhaseShift(test_image[0][1], wires=0)
    ### CORRECCION DE FASE ###
    qml.Barrier()
    qml.X(wires=1)
    qml.ControlledPhaseShift(-test_image[0][1], wires=[0,1])
    qml.X(wires=1)
    qml.Barrier()
    ##########################
    qml.X(wires=[0]) # Desmarcado
    qml.Barrier()
    ####################################
    # qml.H(wires=[0])
    # qml.H(wires=[1])
    return qml.state()

b0_states = [[0,1],[1,0],[1,1]]
b0_phase = 0
b0_fixed = "00"
for i in range(len(b0_states)):
  x = b0_states[i][0]
  y = b0_states[i][1]
  dot = bitwise_dot_product(b0_fixed, [x,y])
  print(test_image_encoded[x][y])
  b0_phase += np.exp(1j*test_image_encoded[x][y])*np.power(-1, dot)
  print(b0_phase)

b0 = (1/(2**q_num))*b0_phase
print(b0)

q_num = 2
test_image = np.array([[1.0, 25],[120, 255]])
test_image_encoded = (test_image*np.pi)/255
print(qml.draw_mpl(my_quantum_function)(test_image_encoded))

inner_0 = np.vdot(b0, b0)        # ⟨ψ|φ⟩   (np.vdot handles conjugation)
# inner_0 = b0
b0_prob  = np.abs(inner_0)**2         # |α|²
print(b0_prob)
pixel_0 = results2[0] - b0_prob
print(pixel_0)

dev = qml.device("default.qubit", wires=2)

img = np.array([1,25, 120,255])

n_qubits = 2

@qml.qnode(dev)
def circuito(img):
    for i in range(n_qubits):
        qml.Hadamard(wires=i)


    qml.Barrier()
    for i in range(n_qubits):
        qml.PauliX(wires=i)

    qml.CPhase(img[0]*np.pi/255, wires=[0,1])

    for i in range(n_qubits):
        qml.PauliX(wires=i)

    qml.Barrier()
    qml.PauliX(wires=0)
    qml.CPhase(img[1]*np.pi/255, wires=[0,1])
    qml.PauliX(wires=0)


    qml.Barrier()
    qml.PauliX(wires=1)
    qml.CPhase(img[2]*np.pi/255, wires=[1,0])
    qml.PauliX(wires=1)

    qml.Barrier()
    qml.CPhase(img[3]*np.pi/255, wires=[0,1])

    return qml.state()

print(qml.draw_mpl(circuito)(img=img))

print(circuito(img))

"""### Complete encoding (2x2 image)"""

def iqft(wires):
    """
    Inverse Quantum Fourier Transform (iQFT) from scratch.

    Args:
        wires (Sequence[int] or Sequence[str]): wires in the register order.
    """

    n = len(wires)

    # ------------------------------------------------------------
    # Step 1) Bit-reversal via SWAPs (reverse wire order)
    # ------------------------------------------------------------
    for i in range(n // 2):
        qml.SWAP(wires=[wires[i], wires[n - 1 - i]])

    # ------------------------------------------------------------
    # Step 2) Core iQFT layers
    #   For each target wire j (from 0 to n-1):
    #     - apply controlled phases from higher-index wires k>j
    #     - then apply Hadamard on wire j
    # ------------------------------------------------------------
    for j in range(n):
        # Controlled phase rotations with negative angles
        # control: wires[k], target: wires[j]
        for k in range(j + 1, n):
            angle = -np.pi / (2 ** (k - j))
            qml.ControlledPhaseShift(angle, wires=[wires[k], wires[j]])

        # Hadamard at the end of this stage
        qml.Hadamard(wires=wires[j])

def bitwise_dot_product(a,b):
  res_dot = 0
  for i in range(len(a)):
    res_dot += int(a[i])*int(b[i])
  res_dot = res_dot % 2
  return res_dot

dev = qml.device('default.qubit', wires=2)
@qml.qnode(dev)
def my_quantum_function(test_image):
    qml.H(wires=[0])
    qml.H(wires=1)
    qml.Barrier()
    ####################################
    ### ORACULO PARA CODIFICAR |00> ###
    qml.X(wires=0) # Marcado
    qml.X(wires=1)
    qml.H(wires=[1])
    qml.CNOT(wires=[0,1])
    qml.PhaseShift(test_image[0][0], wires=0)
    qml.H(wires=[1])
    ### CORRECCION DE FASE ###
    qml.X(wires=1)
    qml.ControlledPhaseShift(-test_image[0][0], wires=[0,1])
    qml.X(wires=1)
    ##########################
    qml.X(wires=[0]) # Desmarcado
    qml.X(wires=[1])
    qml.Barrier()
    ####################################
    ### ORACULO PARA CODIFICAR |01> ###
    qml.X(wires=[0]) # Marcado
    qml.H(wires=[1])
    qml.CNOT(wires=[0,1])
    qml.PhaseShift(test_image[0][1], wires=0)
    qml.H(wires=[1])
    ### CORRECCION DE FASE ###
    qml.X(wires=1)
    qml.ControlledPhaseShift(-test_image[0][1], wires=[0,1])
    qml.X(wires=1)
    ##########################
    qml.X(wires=[0]) # Desmarcado
    qml.Barrier()
    ####################################
    ### ORACULO PARA CODIFICAR |10> ###
    qml.X(wires=[1]) # Marcado
    qml.H(wires=[1])
    qml.CNOT(wires=[0,1])
    qml.PhaseShift(test_image[1][0], wires=0)
    qml.H(wires=[1])
    ### CORRECCION DE FASE ###
    qml.X(wires=1)
    qml.ControlledPhaseShift(-test_image[1][0], wires=[0,1])
    qml.X(wires=1)
    ##########################
    qml.X(wires=[1]) # Desmarcado
    qml.Barrier()
    ####################################
    ### ORACULO PARA CODIFICAR |11> ###
    qml.H(wires=[1])
    qml.CNOT(wires=[0,1])
    qml.PhaseShift(test_image[1][1], wires=0)
    qml.H(wires=[1])
    ### CORRECCION DE FASE ###
    qml.X(wires=1)
    qml.ControlledPhaseShift(-test_image[1][1], wires=[0,1])
    qml.X(wires=1)
    qml.Barrier()
    #################### QUANTUM INTERFERENCE** ##################
    # qml.H(wires=[0])
    # qml.H(wires=[1])
    ####################### INVERSE QFT ##########################
    # wires = range(2)
    # n = len(wires)
    # # # Step 1) Bit-reversal via SWAPs (reverse wire order)
    # for i in range(n // 2):
    #     qml.SWAP(wires=[wires[i], wires[n - 1 - i]])

    # # ------------------------------------------------------------
    # # Step 2) Core iQFT layers
    # #   For each target wire j (from 0 to n-1):
    # #     - apply controlled phases from higher-index wires k>j
    # #     - then apply Hadamard on wire j
    # # ------------------------------------------------------------
    # for j in range(n):
    #     # Controlled phase rotations with negative angles
    #     # control: wires[k], target: wires[j]
    #     for k in range(j + 1, n):
    #         angle = -np.pi / (2 ** (k - j))
    #         qml.ControlledPhaseShift(angle, wires=[wires[k], wires[j]])
    #         # qml.ControlledPhaseShift(angle, wires=[wires[j], wires[k]])

    #     # Hadamard at the end of this stage
    #     qml.Hadamard(wires=wires[j])

    ########################################################################

    return qml.state(), qml.probs(wires=[0,1])

q_num = 2
test_image = np.array([[0, 25],[120, 254]])
test_image_encoded = (test_image*np.pi)/255
print("Original image: ", test_image)
print("Encoded image values: ", test_image_encoded)
results2, results_probs = my_quantum_function(test_image_encoded)
# probs = np.abs(results2)**2
print("State vector Grover encoding: ", results2)
print("Probabilities: ", results_probs)
recovered_image = (results_probs*255)/np.pi*4
print("Recovered image values: ", recovered_image)
print(qml.draw_mpl(my_quantum_function)(test_image_encoded))

import matplotlib.pyplot as plt

# Assuming test_image_encoded is already defined from previous cells
results, results_probs = my_quantum_function(test_image_encoded)

# Extract the real part of the state vector
state_real_part = results.real

# Create a bar plot
plt.figure(figsize=(8, 5))
plt.bar(range(len(state_real_part)), state_real_part)
plt.xlabel("|x⟩")
plt.xticks(range(len(state_real_part)))
# plt.xlim(0, len(state_real_part))
plt.ylabel("Amplitude (real part)")
plt.title("Real Part of Quantum State Amplitudes from my_quantum_function")
plt.show()