# -*- coding: utf-8 -*-
"""Q-PIPE_for_Quantum_Edge_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KBLTA7IQFIG2GXXnU80cYIcHRh66DKwH
"""

!pip install pennylane --quiet

import pennylane as qml
from pennylane import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from sklearn.datasets import load_digits, load_sample_image, fetch_olivetti_faces, fetch_openml
from sklearn.metrics import mean_absolute_error
from skimage.transform import resize
import warnings
warnings.filterwarnings('ignore')

"""# MNIST

## Despalzamiento horizontal (corrigiendo mapeo $-\pi$ a $\pi$)
"""

### CODIFICACIÓN Y DIFERENCIA DE FASES ###
def apply_dual_phases_with_gray_code(flat_phases_1, flat_phases_2, img_wires, est_wire, power):
    n = len(img_wires)
    total_states = 2**n
    gray_seq = [i ^ (i >> 1) for i in range(total_states)]

    for w in img_wires:
        qml.PauliX(wires=w)

    target_wire = img_wires[-1]
    control_wires = [est_wire] + list(img_wires[:-1])

    for step in range(total_states):
        curr_gray = gray_seq[step]
        pixel_idx = curr_gray

        if pixel_idx < len(flat_phases_1):
            phi1 = flat_phases_1[pixel_idx]
            phi2 = flat_phases_2[pixel_idx]

            if abs(phi1) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi1 * power, wires=target_wire)
            if abs(phi2) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi2 * power, wires=target_wire)

        if step < total_states - 1:
            next_gray = gray_seq[step + 1]
            diff = curr_gray ^ next_gray
            bit_changed_from_right = int(np.log2(diff))
            wire_to_flip = img_wires[n - 1 - bit_changed_from_right]
            qml.PauliX(wires=wire_to_flip)

    last_gray_bin = format(gray_seq[-1], f'0{n}b')
    for i, bit in enumerate(last_gray_bin):
        if bit == '0':
            qml.PauliX(wires=img_wires[i])

## Parametros del circuito cuántico
n_pixels = 64
n_image_wires = 6
n_estimation_wires = 8
total_wires = n_estimation_wires + n_image_wires

dev = qml.device('default.qubit', wires=total_wires)

@qml.qnode(dev)
def edge_detection_circuit(flat_p1, flat_p2):
    est_wires = list(range(n_estimation_wires))
    tgt_wires = list(range(n_estimation_wires, total_wires))

    for w in est_wires + tgt_wires:
        qml.Hadamard(wires=w)

    for i, est_wire in enumerate(reversed(est_wires)):
        power = 2**i
        apply_dual_phases_with_gray_code(flat_p1, flat_p2, tgt_wires, est_wire, power)

    qml.adjoint(qml.QFT)(wires=est_wires)
    return qml.probs(wires=est_wires + tgt_wires)

### Cargar datos de dataset "digits"
digits = load_digits()
images_to_test = digits.images[:5]
targets = digits.target[:5]

fig, axes = plt.subplots(5, 4, figsize=(14, 16))

# Umbral (se puede modificar), este umbral debe elegirse usando la "probability threshold equation"
# del arcticulo "Q-PIPE A Practical Quantum Phase Encoding Method".
prob_threshold = 0.01

for idx, raw_img in enumerate(images_to_test):
    raw_img = (raw_img / 16.0) * 255.0

    shifted_img = np.roll(raw_img, shift=1, axis=1)
    shifted_img[:, 0] = 0

    classical_gradient = np.abs(raw_img - shifted_img)

    # CORRECCION: Multiplicamos por pi, no por 2*pi
    phases_base = (raw_img.flatten() / 255.0) * np.pi
    phases_shifted_neg = (-shifted_img.flatten() / 255.0) * np.pi

    print(f"Calculando QPE sin promedio ponderado para dígito {targets[idx]} ({idx+1}/5)...")
    probs = edge_detection_circuit(phases_base, phases_shifted_neg)

    # Revertimos a la asignación directa de matriz
    quantum_edge_img = np.zeros_like(raw_img, dtype=float)

    for k, p in enumerate(probs):
        if p > prob_threshold:
            bin_k = format(k, f'0{total_wires}b')
            est_int = int(bin_k[:n_estimation_wires], 2)
            pixel_idx = int(bin_k[n_estimation_wires:], 2)

            if pixel_idx < n_pixels:
                row, col = np.unravel_index(pixel_idx, raw_img.shape)
                raw_val = (est_int / (2**n_estimation_wires)) * 255.0

                # Decodificación directa compensando el escalamiento
                edge_magnitude = 2.0 * min(raw_val, 255.0 - raw_val)

                # Sobrescribimos valores.
                quantum_edge_img[row, col] = edge_magnitude

    mae_score = mean_absolute_error(classical_gradient.flatten(), quantum_edge_img.flatten())
    print(f"  -> MAE Horizontal (Crudo): {mae_score:.4f}")

    axes[idx, 0].imshow(raw_img, cmap='gray', vmin=0, vmax=255)
    axes[idx, 0].set_title(f"Original: {targets[idx]}")
    axes[idx, 0].axis('off')

    axes[idx, 1].imshow(shifted_img, cmap='gray', vmin=0, vmax=255)
    axes[idx, 1].set_title("Displaced")
    axes[idx, 1].axis('off')

    axes[idx, 2].imshow(classical_gradient, cmap='gray', vmin=0, vmax=255)
    axes[idx, 2].set_title("Classical gradient")
    axes[idx, 2].axis('off')

    axes[idx, 3].imshow(np.clip(quantum_edge_img, 0, 255), cmap='gray', vmin=0, vmax=255)
    axes[idx, 3].set_title(f"Q-PIPE gradient \nMAE: {mae_score:.2f}")
    axes[idx, 3].axis('off')

plt.tight_layout()
plt.savefig("edge_detection_circuit_mnist_horizontal.png", dpi=600)
plt.savefig("edge_detection_circuit_mnist_horizontal.eps")
plt.show()
print("Procesamiento cuántico de comparación finalizado.")

"""## Desplazamiento horizontal (corrigiendo mapeo $-\pi$ a $\pi$ + spectral leakage)"""

### CODIFICACIÓN Y DIFERENCIA DE FASES (desplazamiento horizontal) ###
def apply_dual_phases_with_gray_code(flat_phases_1, flat_phases_2, img_wires, est_wire, power):
    n = len(img_wires)
    total_states = 2**n
    gray_seq = [i ^ (i >> 1) for i in range(total_states)]

    for w in img_wires:
        qml.PauliX(wires=w)

    target_wire = img_wires[-1]
    control_wires = [est_wire] + list(img_wires[:-1])

    for step in range(total_states):
        curr_gray = gray_seq[step]
        pixel_idx = curr_gray

        if pixel_idx < len(flat_phases_1):
            phi1 = flat_phases_1[pixel_idx]
            phi2 = flat_phases_2[pixel_idx]

            if abs(phi1) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi1 * power, wires=target_wire)
            if abs(phi2) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi2 * power, wires=target_wire)

        if step < total_states - 1:
            next_gray = gray_seq[step + 1]
            diff = curr_gray ^ next_gray
            bit_changed_from_right = int(np.log2(diff))
            wire_to_flip = img_wires[n - 1 - bit_changed_from_right]
            qml.PauliX(wires=wire_to_flip)

    last_gray_bin = format(gray_seq[-1], f'0{n}b')
    for i, bit in enumerate(last_gray_bin):
        if bit == '0':
            qml.PauliX(wires=img_wires[i])

### Parametros del circuito cuántico ###
n_pixels = 64
n_image_wires = 6
n_estimation_wires = 8
total_wires = n_estimation_wires + n_image_wires

dev = qml.device('default.qubit', wires=total_wires)

@qml.qnode(dev)
def edge_detection_circuit(flat_p1, flat_p2):
    est_wires = list(range(n_estimation_wires))
    tgt_wires = list(range(n_estimation_wires, total_wires))

    for w in est_wires + tgt_wires:
        qml.Hadamard(wires=w)

    for i, est_wire in enumerate(reversed(est_wires)):
        power = 2**i
        apply_dual_phases_with_gray_code(flat_p1, flat_p2, tgt_wires, est_wire, power)

    qml.adjoint(qml.QFT)(wires=est_wires)
    return qml.probs(wires=est_wires + tgt_wires)

## Cargar dataset "digits"
digits = load_digits()
images_to_test = digits.images[:5]
targets = digits.target[:5]

fig, axes = plt.subplots(5, 4, figsize=(14, 16))

# Umbral (puede modificarse) para 8 qubits de estimación.
prob_threshold = 0.01

for idx, raw_img in enumerate(images_to_test):
    raw_img = (raw_img / 16.0) * 255.0

    shifted_img = np.roll(raw_img, shift=1, axis=1)
    shifted_img[:, 0] = 0

    classical_gradient = np.abs(raw_img - shifted_img)

    ## CORRECCIÓN: Multiplicamos por pi, no por 2*pi ##
    phases_base = (raw_img.flatten() / 255.0) * np.pi
    phases_shifted_neg = (-shifted_img.flatten() / 255.0) * np.pi

    print(f"Calculando QPE para dígito {targets[idx]} ({idx+1}/5)...")
    probs = edge_detection_circuit(phases_base, phases_shifted_neg)

    weighted_mag_sum = np.zeros_like(raw_img, dtype=float)
    prob_sum = np.zeros_like(raw_img, dtype=float)

    for k, p in enumerate(probs):
        if p > prob_threshold:
            bin_k = format(k, f'0{total_wires}b')
            est_int = int(bin_k[:n_estimation_wires], 2)
            pixel_idx = int(bin_k[n_estimation_wires:], 2)

            if pixel_idx < n_pixels:
                row, col = np.unravel_index(pixel_idx, raw_img.shape)
                raw_val = (est_int / (2**n_estimation_wires)) * 255.0

                # Nueva decodificación: Como mapeamos a la mitad de la fase (pi),
                # la magnitud real es el doble de la distancia extraída.
                edge_magnitude = 2.0 * min(raw_val, 255.0 - raw_val)

                weighted_mag_sum[row, col] += p * edge_magnitude
                prob_sum[row, col] += p

    safe_prob_sum = np.where(prob_sum == 0, 1.0, prob_sum)
    quantum_edge_img = weighted_mag_sum / safe_prob_sum

    mae_score = mean_absolute_error(classical_gradient.flatten(), quantum_edge_img.flatten())
    print(f"  -> MAE Horizontal: {mae_score:.4f}")

    # Visualización
    axes[idx, 0].imshow(raw_img, cmap='gray', vmin=0, vmax=255)
    axes[idx, 0].set_title(f"Original: {targets[idx]}")
    axes[idx, 0].axis('off')

    axes[idx, 1].imshow(shifted_img, cmap='gray', vmin=0, vmax=255)
    axes[idx, 1].set_title("Displaced")
    axes[idx, 1].axis('off')

    axes[idx, 2].imshow(classical_gradient, cmap='gray', vmin=0, vmax=255)
    axes[idx, 2].set_title("Classical gradient")
    axes[idx, 2].axis('off')

    axes[idx, 3].imshow(np.clip(quantum_edge_img, 0, 255), cmap='gray', vmin=0, vmax=255)
    axes[idx, 3].set_title(f"Q-PIPE gradient \nMAE: {mae_score:.2f}")
    axes[idx, 3].axis('off')

plt.tight_layout()
plt.savefig("edge_detection_circuit_mnist_horizontal.png", dpi=600)
plt.savefig("edge_detection_circuit_mnist_horizontal.eps")
plt.show()
print("Procesamiento cuántico corregido finalizado.")

## Q-PIPE (circuito cuantico)
def apply_dual_phases_with_gray_code(flat_phases_1, flat_phases_2, img_wires, est_wire, power):
    n = len(img_wires)
    total_states = 2**n
    gray_seq = [i ^ (i >> 1) for i in range(total_states)]

    for w in img_wires:
        qml.PauliX(wires=w)

    target_wire = img_wires[-1]
    control_wires = [est_wire] + list(img_wires[:-1])

    for step in range(total_states):
        curr_gray = gray_seq[step]
        pixel_idx = curr_gray

        if pixel_idx < len(flat_phases_1):
            phi1 = flat_phases_1[pixel_idx]
            phi2 = flat_phases_2[pixel_idx]

            if abs(phi1) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi1 * power, wires=target_wire)
            if abs(phi2) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi2 * power, wires=target_wire)

        if step < total_states - 1:
            next_gray = gray_seq[step + 1]
            diff = curr_gray ^ next_gray
            bit_changed_from_right = int(np.log2(diff))
            wire_to_flip = img_wires[n - 1 - bit_changed_from_right]
            qml.PauliX(wires=wire_to_flip)

    last_gray_bin = format(gray_seq[-1], f'0{n}b')
    for i, bit in enumerate(last_gray_bin):
        if bit == '0':
            qml.PauliX(wires=img_wires[i])

## Parametros del circuito
n_pixels = 64
n_image_wires = 6
n_estimation_wires = 8
total_wires = n_estimation_wires + n_image_wires

dev = qml.device('default.qubit', wires=total_wires)

@qml.qnode(dev)
def edge_detection_circuit(flat_p1, flat_p2):
    est_wires = list(range(n_estimation_wires))
    tgt_wires = list(range(n_estimation_wires, total_wires))

    for w in est_wires + tgt_wires:
        qml.Hadamard(wires=w)

    for i, est_wire in enumerate(reversed(est_wires)):
        power = 2**i
        apply_dual_phases_with_gray_code(flat_p1, flat_p2, tgt_wires, est_wire, power)

    qml.adjoint(qml.QFT)(wires=est_wires)
    return qml.probs(wires=est_wires + tgt_wires)

def run_qpipe_horizontal(raw_img, prob_threshold=0.0005):
    shifted_img = np.roll(raw_img, shift=1, axis=1)
    shifted_img[:, 0] = 0
    classical_gradient = np.abs(raw_img - shifted_img)

    phases_base = (raw_img.flatten() / 255.0) * np.pi
    phases_shifted_neg = (-shifted_img.flatten() / 255.0) * np.pi

    probs = edge_detection_circuit(phases_base, phases_shifted_neg)

    weighted_mag_sum = np.zeros_like(raw_img, dtype=float)
    prob_sum = np.zeros_like(raw_img, dtype=float)

    for k, p in enumerate(probs):
        if p > prob_threshold:
            bin_k = format(k, f'0{total_wires}b')
            est_int = int(bin_k[:n_estimation_wires], 2)
            pixel_idx = int(bin_k[n_estimation_wires:], 2)

            if pixel_idx < n_pixels:
                row, col = np.unravel_index(pixel_idx, raw_img.shape)
                raw_val = (est_int / (2**n_estimation_wires)) * 255.0
                edge_magnitude = 2.0 * min(raw_val, 255.0 - raw_val)
                weighted_mag_sum[row, col] += p * edge_magnitude
                prob_sum[row, col] += p

    safe_prob_sum = np.where(prob_sum == 0, 1.0, prob_sum)
    quantum_edge_img = weighted_mag_sum / safe_prob_sum
    mae_score = mean_absolute_error(classical_gradient.flatten(), quantum_edge_img.flatten())

    return shifted_img, classical_gradient, quantum_edge_img, mae_score

## Datasets
print("Loading datasets...")

# MNIST: load_digits (Discreto, 8x8 nativo)
digits = load_digits()
images_discrete = [(img / 16.0) * 255.0 for img in digits.images[:5]]
targets = digits.target[:5]

# OpenML MNIST: fetch_openml (Continuo, 28x28 interpolado a 8x8)
mnist_data = fetch_openml('mnist_784', version=1, cache=True, parser='auto')
X_cont = mnist_data.data.values.reshape(-1, 28, 28)
y_cont = mnist_data.target.values.astype(int)

images_continuous = []
for t in targets:
    idx = np.where(y_cont == t)[0][0]
    img_resized = resize(X_cont[idx], (8, 8), anti_aliasing=True, preserve_range=True)
    img_normalized = (img_resized / np.max(img_resized)) * 255.0
    images_continuous.append(img_normalized)

## Visualizacion
fig = plt.figure(figsize=(25, 17))
# 9 columnas: 4 para discreto, 1 separador (ancho 0.2), 4 para continuo
gs = gridspec.GridSpec(5, 9, width_ratios=[1, 1, 1, 1, 0.2, 1, 1, 1, 1])

for idx in range(5):
    print(f"Processing digit {targets[idx]} ({idx+1}/5)...")

    raw_discrete = images_discrete[idx]
    raw_cont = images_continuous[idx]

    shift_disc, class_grad_disc, q_grad_disc, mae_disc = run_qpipe_horizontal(raw_discrete)
    shift_cont, class_grad_cont, q_grad_cont, mae_cont = run_qpipe_horizontal(raw_cont)

    # --- Bloque Izquierdo: MNIST Discreto ---
    ax0 = fig.add_subplot(gs[idx, 0])
    ax0.imshow(raw_discrete, cmap='gray', vmin=0, vmax=255)
    ax0.set_title(f"Original (Discrete): {targets[idx]}")
    ax0.axis('off')

    ax1 = fig.add_subplot(gs[idx, 1])
    ax1.imshow(shift_disc, cmap='gray', vmin=0, vmax=255)
    ax1.set_title("Displaced")
    ax1.axis('off')

    ax2 = fig.add_subplot(gs[idx, 2])
    ax2.imshow(class_grad_disc, cmap='gray', vmin=0, vmax=255)
    ax2.set_title("Classical Gradient")
    ax2.axis('off')

    ax3 = fig.add_subplot(gs[idx, 3])
    ax3.imshow(np.clip(q_grad_disc, 0, 255), cmap='gray', vmin=0, vmax=255)
    ax3.set_title(f"Q-PIPE Gradient\nMAE: {mae_disc:.2f}")
    ax3.axis('off')

    # gs[idx, 4] actúa como espacio en blanco separador

    # --- Bloque Derecho: MNIST Continuo (OpenML) ---
    ax5 = fig.add_subplot(gs[idx, 5])
    ax5.imshow(raw_cont, cmap='gray', vmin=0, vmax=255)
    ax5.set_title(f"Original (Continuous): {targets[idx]}")
    ax5.axis('off')

    ax6 = fig.add_subplot(gs[idx, 6])
    ax6.imshow(shift_cont, cmap='gray', vmin=0, vmax=255)
    ax6.set_title("Displaced")
    ax6.axis('off')

    ax7 = fig.add_subplot(gs[idx, 7])
    ax7.imshow(class_grad_cont, cmap='gray', vmin=0, vmax=255)
    ax7.set_title("Classical Gradient")
    ax7.axis('off')

    ax8 = fig.add_subplot(gs[idx, 8])
    ax8.imshow(np.clip(q_grad_cont, 0, 255), cmap='gray', vmin=0, vmax=255)
    ax8.set_title(f"Q-PIPE Gradient\nMAE: {mae_cont:.2f}")
    ax8.axis('off')

plt.tight_layout()
plt.savefig("edge_detection_mnist_dual_subplot.png", dpi=600)
plt.savefig("edge_detection_mnist_dual_subplot.eps")
plt.show()
print("Quantum comparative processing finished.")

"""## Desplazamiento vectical (corrigiendo mapeo $-\pi$ a $\pi$)"""

### CODIFICACIÓN Y DIFERENCIA DE FASES (desplazamiento vertical) ###
def apply_dual_phases_with_gray_code(flat_phases_1, flat_phases_2, img_wires, est_wire, power):
    n = len(img_wires)
    total_states = 2**n
    gray_seq = [i ^ (i >> 1) for i in range(total_states)]

    for w in img_wires:
        qml.PauliX(wires=w)

    target_wire = img_wires[-1]
    control_wires = [est_wire] + list(img_wires[:-1])

    for step in range(total_states):
        curr_gray = gray_seq[step]
        pixel_idx = curr_gray

        if pixel_idx < len(flat_phases_1):
            phi1 = flat_phases_1[pixel_idx]
            phi2 = flat_phases_2[pixel_idx]

            if abs(phi1) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi1 * power, wires=target_wire)
            if abs(phi2) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi2 * power, wires=target_wire)

        if step < total_states - 1:
            next_gray = gray_seq[step + 1]
            diff = curr_gray ^ next_gray
            bit_changed_from_right = int(np.log2(diff))
            wire_to_flip = img_wires[n - 1 - bit_changed_from_right]
            qml.PauliX(wires=wire_to_flip)

    last_gray_bin = format(gray_seq[-1], f'0{n}b')
    for i, bit in enumerate(last_gray_bin):
        if bit == '0':
            qml.PauliX(wires=img_wires[i])

## Parametros del circuito cuántico
n_pixels = 64
n_image_wires = 6
n_estimation_wires = 8
total_wires = n_estimation_wires + n_image_wires

dev = qml.device('default.qubit', wires=total_wires)

@qml.qnode(dev)
def edge_detection_circuit(flat_p1, flat_p2):
    est_wires = list(range(n_estimation_wires))
    tgt_wires = list(range(n_estimation_wires, total_wires))

    for w in est_wires + tgt_wires:
        qml.Hadamard(wires=w)

    for i, est_wire in enumerate(reversed(est_wires)):
        power = 2**i
        apply_dual_phases_with_gray_code(flat_p1, flat_p2, tgt_wires, est_wire, power)

    qml.adjoint(qml.QFT)(wires=est_wires)
    return qml.probs(wires=est_wires + tgt_wires)

## Carga dataset
digits = load_digits()
images_to_test = digits.images[:5]
targets = digits.target[:5]

fig, axes = plt.subplots(5, 4, figsize=(14, 16))

prob_threshold = 0.001

for idx, raw_img in enumerate(images_to_test):
    # Normalización
    raw_img = (raw_img / 16.0) * 255.0

    # Preprocesamiento: Desp. VERTICAL (axis=0)
    shifted_img_y = np.roll(raw_img, shift=1, axis=0)
    shifted_img_y[0, :] = 0

    classical_gradient_y = np.abs(raw_img - shifted_img_y)

    # Escalamiento de media fase.
    phases_base = (raw_img.flatten() / 255.0) * np.pi
    phases_shifted_neg_y = (-shifted_img_y.flatten() / 255.0) * np.pi

    print(f"Calculando QPE Vertical para dígito {targets[idx]} ({idx+1}/5)...")
    probs = edge_detection_circuit(phases_base, phases_shifted_neg_y)

    weighted_mag_sum = np.zeros_like(raw_img, dtype=float)
    prob_sum = np.zeros_like(raw_img, dtype=float)

    for k, p in enumerate(probs):
        if p > prob_threshold:
            bin_k = format(k, f'0{total_wires}b')
            est_int = int(bin_k[:n_estimation_wires], 2)
            pixel_idx = int(bin_k[n_estimation_wires:], 2)

            if pixel_idx < n_pixels:
                row, col = np.unravel_index(pixel_idx, raw_img.shape)
                raw_val = (est_int / (2**n_estimation_wires)) * 255.0

                # Decodificación y ajuste de escala x2
                edge_magnitude = 2.0 * min(raw_val, 255.0 - raw_val)

                weighted_mag_sum[row, col] += p * edge_magnitude
                prob_sum[row, col] += p

    safe_prob_sum = np.where(prob_sum == 0, 1.0, prob_sum)
    quantum_edge_img_y = weighted_mag_sum / safe_prob_sum

    mae_score = mean_absolute_error(classical_gradient_y.flatten(), quantum_edge_img_y.flatten()) # Métrica
    print(f"  -> MAE Vertical: {mae_score:.4f}")

    # Visualización
    axes[idx, 0].imshow(raw_img, cmap='gray', vmin=0, vmax=255)
    axes[idx, 0].set_title(f"Original: {targets[idx]}")
    axes[idx, 0].axis('off')

    axes[idx, 1].imshow(shifted_img_y, cmap='gray', vmin=0, vmax=255)
    axes[idx, 1].set_title("Displaced")
    axes[idx, 1].axis('off')

    axes[idx, 2].imshow(classical_gradient_y, cmap='gray', vmin=0, vmax=255)
    axes[idx, 2].set_title("Classical gradient")
    axes[idx, 2].axis('off')

    axes[idx, 3].imshow(np.clip(quantum_edge_img_y, 0, 255), cmap='gray', vmin=0, vmax=255)
    axes[idx, 3].set_title(f"Q-PIPE gradient \nMAE: {mae_score:.2f}")
    axes[idx, 3].axis('off')

plt.tight_layout()
plt.savefig("edge_detection_circuit_mnist_vertical.png", dpi=600)
plt.savefig("edge_detection_circuit_mnist_vertical.eps")
plt.show()
print("Procesamiento cuántico vertical finalizado.")

# ==========================================
# 1. Oráculo Q-PIPE (Código Gray)
# ==========================================
def apply_dual_phases_with_gray_code(flat_phases_1, flat_phases_2, img_wires, est_wire, power):
    n = len(img_wires)
    total_states = 2**n
    gray_seq = [i ^ (i >> 1) for i in range(total_states)]

    for w in img_wires:
        qml.PauliX(wires=w)

    target_wire = img_wires[-1]
    control_wires = [est_wire] + list(img_wires[:-1])

    for step in range(total_states):
        curr_gray = gray_seq[step]
        pixel_idx = curr_gray

        if pixel_idx < len(flat_phases_1):
            phi1 = flat_phases_1[pixel_idx]
            phi2 = flat_phases_2[pixel_idx]

            if abs(phi1) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi1 * power, wires=target_wire)
            if abs(phi2) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi2 * power, wires=target_wire)

        if step < total_states - 1:
            next_gray = gray_seq[step + 1]
            diff = curr_gray ^ next_gray
            bit_changed_from_right = int(np.log2(diff))
            wire_to_flip = img_wires[n - 1 - bit_changed_from_right]
            qml.PauliX(wires=wire_to_flip)

    last_gray_bin = format(gray_seq[-1], f'0{n}b')
    for i, bit in enumerate(last_gray_bin):
        if bit == '0':
            qml.PauliX(wires=img_wires[i])

# ==========================================
# 2. Configuración del Circuito Cuántico
# ==========================================
n_pixels = 64
n_image_wires = 6
n_estimation_wires = 8
total_wires = n_estimation_wires + n_image_wires

dev = qml.device('default.qubit', wires=total_wires)

@qml.qnode(dev)
def edge_detection_circuit(flat_p1, flat_p2):
    est_wires = list(range(n_estimation_wires))
    tgt_wires = list(range(n_estimation_wires, total_wires))

    for w in est_wires + tgt_wires:
        qml.Hadamard(wires=w)

    for i, est_wire in enumerate(reversed(est_wires)):
        power = 2**i
        apply_dual_phases_with_gray_code(flat_p1, flat_p2, tgt_wires, est_wire, power)

    qml.adjoint(qml.QFT)(wires=est_wires)
    return qml.probs(wires=est_wires + tgt_wires)

# Motor modular para procesamiento VERTICAL
def run_qpipe_vertical(raw_img, prob_threshold=0.0005):
    # Cambio algorítmico crítico: Desplazamiento sobre axis=0 (filas)
    shifted_img = np.roll(raw_img, shift=1, axis=0)
    shifted_img[0, :] = 0  # Limpiar artefacto de envoltura en la frontera superior

    classical_gradient = np.abs(raw_img - shifted_img)

    phases_base = (raw_img.flatten() / 255.0) * np.pi
    phases_shifted_neg = (-shifted_img.flatten() / 255.0) * np.pi

    probs = edge_detection_circuit(phases_base, phases_shifted_neg)

    weighted_mag_sum = np.zeros_like(raw_img, dtype=float)
    prob_sum = np.zeros_like(raw_img, dtype=float)

    for k, p in enumerate(probs):
        if p > prob_threshold:
            bin_k = format(k, f'0{total_wires}b')
            est_int = int(bin_k[:n_estimation_wires], 2)
            pixel_idx = int(bin_k[n_estimation_wires:], 2)

            if pixel_idx < n_pixels:
                row, col = np.unravel_index(pixel_idx, raw_img.shape)
                raw_val = (est_int / (2**n_estimation_wires)) * 255.0
                edge_magnitude = 2.0 * min(raw_val, 255.0 - raw_val)
                weighted_mag_sum[row, col] += p * edge_magnitude
                prob_sum[row, col] += p

    safe_prob_sum = np.where(prob_sum == 0, 1.0, prob_sum)
    quantum_edge_img = weighted_mag_sum / safe_prob_sum
    mae_score = mean_absolute_error(classical_gradient.flatten(), quantum_edge_img.flatten())

    return shifted_img, classical_gradient, quantum_edge_img, mae_score

# ==========================================
# 3. Preparación de Datasets
# ==========================================
print("Loading datasets...")

digits = load_digits()
images_discrete = [(img / 16.0) * 255.0 for img in digits.images[:5]]
targets = digits.target[:5]

mnist_data = fetch_openml('mnist_784', version=1, cache=True, parser='auto')
X_cont = mnist_data.data.values.reshape(-1, 28, 28)
y_cont = mnist_data.target.values.astype(int)

images_continuous = []
for t in targets:
    idx = np.where(y_cont == t)[0][0]
    img_resized = resize(X_cont[idx], (8, 8), anti_aliasing=True, preserve_range=True)
    img_normalized = (img_resized / np.max(img_resized)) * 255.0
    images_continuous.append(img_normalized)

# ==========================================
# 4. Visualización Comparativa (Doble Subgráfica)
# ==========================================
fig = plt.figure(figsize=(25, 17))
gs = gridspec.GridSpec(5, 9, width_ratios=[1, 1, 1, 1, 0.2, 1, 1, 1, 1])

for idx in range(5):
    print(f"Processing digit {targets[idx]} ({idx+1}/5)...")

    raw_discrete = images_discrete[idx]
    raw_cont = images_continuous[idx]

    shift_disc, class_grad_disc, q_grad_disc, mae_disc = run_qpipe_vertical(raw_discrete)
    shift_cont, class_grad_cont, q_grad_cont, mae_cont = run_qpipe_vertical(raw_cont)

    # --- Bloque Izquierdo: MNIST Discreto ---
    ax0 = fig.add_subplot(gs[idx, 0])
    ax0.imshow(raw_discrete, cmap='gray', vmin=0, vmax=255)
    ax0.set_title(f"Original (Discrete): {targets[idx]}")
    ax0.axis('off')

    ax1 = fig.add_subplot(gs[idx, 1])
    ax1.imshow(shift_disc, cmap='gray', vmin=0, vmax=255)
    ax1.set_title("Vertical Displaced")
    ax1.axis('off')

    ax2 = fig.add_subplot(gs[idx, 2])
    ax2.imshow(class_grad_disc, cmap='gray', vmin=0, vmax=255)
    ax2.set_title("Classical Gradient (Y)")
    ax2.axis('off')

    ax3 = fig.add_subplot(gs[idx, 3])
    ax3.imshow(np.clip(q_grad_disc, 0, 255), cmap='gray', vmin=0, vmax=255)
    ax3.set_title(f"Q-PIPE Gradient (Y)\nMAE: {mae_disc:.2f}")
    ax3.axis('off')

    # --- Bloque Derecho: MNIST Continuo ---
    ax5 = fig.add_subplot(gs[idx, 5])
    ax5.imshow(raw_cont, cmap='gray', vmin=0, vmax=255)
    ax5.set_title(f"Original (Continuous): {targets[idx]}")
    ax5.axis('off')

    ax6 = fig.add_subplot(gs[idx, 6])
    ax6.imshow(shift_cont, cmap='gray', vmin=0, vmax=255)
    ax6.set_title("Vertical Displaced")
    ax6.axis('off')

    ax7 = fig.add_subplot(gs[idx, 7])
    ax7.imshow(class_grad_cont, cmap='gray', vmin=0, vmax=255)
    ax7.set_title("Classical Gradient (Y)")
    ax7.axis('off')

    ax8 = fig.add_subplot(gs[idx, 8])
    ax8.imshow(np.clip(q_grad_cont, 0, 255), cmap='gray', vmin=0, vmax=255)
    ax8.set_title(f"Q-PIPE Gradient (Y)\nMAE: {mae_cont:.2f}")
    ax8.axis('off')

plt.tight_layout()
plt.savefig("edge_detection_mnist_dual_subplot_vertical.png", dpi=600)
plt.savefig("edge_detection_mnist_dual_subplot_vertical.eps")
plt.show()
print("Vertical quantum comparative processing finished.")

"""## Desplazamiento combinado (metrica de Sobel, corrección de mapeo + spectral leakage)"""

### DESPLAZAMIENTO COMBINADO (SOBEL + mapeo corregido + corrección spectral leakage)
def apply_dual_phases_with_gray_code(flat_phases_1, flat_phases_2, img_wires, est_wire, power):
    n = len(img_wires)
    total_states = 2**n
    gray_seq = [i ^ (i >> 1) for i in range(total_states)]

    for w in img_wires:
        qml.PauliX(wires=w)

    target_wire = img_wires[-1]
    control_wires = [est_wire] + list(img_wires[:-1])

    for step in range(total_states):
        curr_gray = gray_seq[step]
        pixel_idx = curr_gray

        if pixel_idx < len(flat_phases_1):
            phi1 = flat_phases_1[pixel_idx]
            phi2 = flat_phases_2[pixel_idx]

            if abs(phi1) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi1 * power, wires=target_wire)
            if abs(phi2) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi2 * power, wires=target_wire)

        if step < total_states - 1:
            next_gray = gray_seq[step + 1]
            diff = curr_gray ^ next_gray
            bit_changed_from_right = int(np.log2(diff))
            wire_to_flip = img_wires[n - 1 - bit_changed_from_right]
            qml.PauliX(wires=wire_to_flip)

    last_gray_bin = format(gray_seq[-1], f'0{n}b')
    for i, bit in enumerate(last_gray_bin):
        if bit == '0':
            qml.PauliX(wires=img_wires[i])

## Parametros del CC
n_pixels = 64
n_image_wires = 6
n_estimation_wires = 8
total_wires = n_estimation_wires + n_image_wires

dev = qml.device('default.qubit', wires=total_wires)

@qml.qnode(dev)
def edge_detection_circuit(flat_p1, flat_p2):
    est_wires = list(range(n_estimation_wires))
    tgt_wires = list(range(n_estimation_wires, total_wires))

    for w in est_wires + tgt_wires:
        qml.Hadamard(wires=w)

    for i, est_wire in enumerate(reversed(est_wires)):
        power = 2**i
        apply_dual_phases_with_gray_code(flat_p1, flat_p2, tgt_wires, est_wire, power)

    qml.adjoint(qml.QFT)(wires=est_wires)
    return qml.probs(wires=est_wires + tgt_wires)

### Decodificación.
def extract_gradient_magnitude(probs, shape, threshold=0.001):
    weighted_mag_sum = np.zeros(shape, dtype=float)
    prob_sum = np.zeros(shape, dtype=float)

    for k, p in enumerate(probs):
        if p > threshold:
            bin_k = format(k, f'0{total_wires}b')
            est_int = int(bin_k[:n_estimation_wires], 2)
            pixel_idx = int(bin_k[n_estimation_wires:], 2)

            if pixel_idx < n_pixels:
                row, col = np.unravel_index(pixel_idx, shape)
                raw_val = (est_int / (2**n_estimation_wires)) * 255.0

                # Compensación del escalamiento a media fase (x2)
                edge_magnitude = 2.0 * min(raw_val, 255.0 - raw_val)

                weighted_mag_sum[row, col] += p * edge_magnitude
                prob_sum[row, col] += p

    safe_prob_sum = np.where(prob_sum == 0, 1.0, prob_sum)
    return weighted_mag_sum / safe_prob_sum

## Cargar dataset y calcular Sobel clasico y cuántico.
digits = load_digits()
images_to_test = digits.images[:5]
targets = digits.target[:5]

fig, axes = plt.subplots(5, 4, figsize=(14, 16))

for idx, raw_img in enumerate(images_to_test):
    raw_img = (raw_img / 16.0) * 255.0

    # Preprocesamiento
    shifted_x = np.roll(raw_img, shift=1, axis=1); shifted_x[:, 0] = 0
    shifted_y = np.roll(raw_img, shift=1, axis=0); shifted_y[0, :] = 0

    # Escalamiento de media fase.
    phases_base = (raw_img.flatten() / 255.0) * np.pi
    phases_neg_x = (-shifted_x.flatten() / 255.0) * np.pi
    phases_neg_y = (-shifted_y.flatten() / 255.0) * np.pi

    # Sobel cuantico.
    print(f"Ejecutando QPE (Sobel) para dígito {targets[idx]} ({idx+1}/5)...")
    probs_x = edge_detection_circuit(phases_base, phases_neg_x)
    probs_y = edge_detection_circuit(phases_base, phases_neg_y)

    # Decodificación cuántica
    q_gx = extract_gradient_magnitude(probs_x, raw_img.shape)
    q_gy = extract_gradient_magnitude(probs_y, raw_img.shape)

    # Fusión híbrida (Norma L2)
    quantum_sobel = np.sqrt(q_gx**2 + q_gy**2)

    # Ground Truth (clásico)
    c_gx = np.abs(raw_img - shifted_x)
    c_gy = np.abs(raw_img - shifted_y)
    classic_sobel = np.sqrt(c_gx**2 + c_gy**2)

    mae_score = mean_absolute_error(classic_sobel.flatten(), quantum_sobel.flatten())
    print(f"  -> MAE Sobel Total: {mae_score:.4f}")

    # Visualización
    axes[idx, 0].imshow(raw_img, cmap='gray', vmin=0, vmax=255)
    axes[idx, 0].set_title(f"Original: {targets[idx]}")
    axes[idx, 0].axis('off')

    axes[idx, 1].imshow(np.clip(q_gx + q_gy, 0, 255), cmap='gray', vmin=0, vmax=255)
    axes[idx, 1].set_title("QED components\n($|G_x| + |G_y|$)")
    axes[idx, 1].axis('off')

    axes[idx, 2].imshow(np.clip(classic_sobel, 0, 255), cmap='gray', vmin=0, vmax=255)
    axes[idx, 2].set_title("Classic Sobel\n$\sqrt{G_x^2 + G_y^2}$")
    axes[idx, 2].axis('off')

    axes[idx, 3].imshow(np.clip(quantum_sobel, 0, 255), cmap='gray', vmin=0, vmax=255)
    axes[idx, 3].set_title(f"Q-PIPE Sobel \nMAE: {mae_score:.2f}")
    axes[idx, 3].axis('off')

plt.tight_layout()
plt.savefig("sobel_edge_detection_mnist.png", dpi=600)
plt.savefig("sobel_edge_detection_mnist.eps")
plt.show()
print("Procesamiento híbrido Sobel finalizado.")

# ==========================================
# 1. Oráculo Q-PIPE (Código Gray)
# ==========================================
def apply_dual_phases_with_gray_code(flat_phases_1, flat_phases_2, img_wires, est_wire, power):
    n = len(img_wires)
    total_states = 2**n
    gray_seq = [i ^ (i >> 1) for i in range(total_states)]

    for w in img_wires:
        qml.PauliX(wires=w)

    target_wire = img_wires[-1]
    control_wires = [est_wire] + list(img_wires[:-1])

    for step in range(total_states):
        curr_gray = gray_seq[step]
        pixel_idx = curr_gray

        if pixel_idx < len(flat_phases_1):
            phi1 = flat_phases_1[pixel_idx]
            phi2 = flat_phases_2[pixel_idx]

            if abs(phi1) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi1 * power, wires=target_wire)
            if abs(phi2) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi2 * power, wires=target_wire)

        if step < total_states - 1:
            next_gray = gray_seq[step + 1]
            diff = curr_gray ^ next_gray
            bit_changed_from_right = int(np.log2(diff))
            wire_to_flip = img_wires[n - 1 - bit_changed_from_right]
            qml.PauliX(wires=wire_to_flip)

    last_gray_bin = format(gray_seq[-1], f'0{n}b')
    for i, bit in enumerate(last_gray_bin):
        if bit == '0':
            qml.PauliX(wires=img_wires[i])

# ==========================================
# 2. Configuración del Circuito Cuántico
# ==========================================
n_pixels = 64
n_image_wires = 6
n_estimation_wires = 8
total_wires = n_estimation_wires + n_image_wires

dev = qml.device('default.qubit', wires=total_wires)

@qml.qnode(dev)
def edge_detection_circuit(flat_p1, flat_p2):
    est_wires = list(range(n_estimation_wires))
    tgt_wires = list(range(n_estimation_wires, total_wires))

    for w in est_wires + tgt_wires:
        qml.Hadamard(wires=w)

    for i, est_wire in enumerate(reversed(est_wires)):
        power = 2**i
        apply_dual_phases_with_gray_code(flat_p1, flat_p2, tgt_wires, est_wire, power)

    qml.adjoint(qml.QFT)(wires=est_wires)
    return qml.probs(wires=est_wires + tgt_wires)

# Extracción modular de magnitud
def extract_magnitude(probs, shape, prob_threshold=0.0005):
    weighted_mag_sum = np.zeros(shape, dtype=float)
    prob_sum = np.zeros(shape, dtype=float)

    for k, p in enumerate(probs):
        if p > prob_threshold:
            bin_k = format(k, f'0{total_wires}b')
            est_int = int(bin_k[:n_estimation_wires], 2)
            pixel_idx = int(bin_k[n_estimation_wires:], 2)

            if pixel_idx < n_pixels:
                row, col = np.unravel_index(pixel_idx, shape)
                raw_val = (est_int / (2**n_estimation_wires)) * 255.0
                edge_magnitude = 2.0 * min(raw_val, 255.0 - raw_val)
                weighted_mag_sum[row, col] += p * edge_magnitude
                prob_sum[row, col] += p

    safe_prob_sum = np.where(prob_sum == 0, 1.0, prob_sum)
    return weighted_mag_sum / safe_prob_sum

# Motor Híbrido Completo (Sobel L2)
def run_qpipe_sobel(raw_img):
    # Desplazamientos Clásicos
    shifted_x = np.roll(raw_img, shift=1, axis=1); shifted_x[:, 0] = 0
    shifted_y = np.roll(raw_img, shift=1, axis=0); shifted_y[0, :] = 0

    # Ground Truth Clásico
    c_gx = np.abs(raw_img - shifted_x)
    c_gy = np.abs(raw_img - shifted_y)
    classic_sobel = np.sqrt(c_gx**2 + c_gy**2)

    # Inyección de Fase Q-PIPE
    phases_base = (raw_img.flatten() / 255.0) * np.pi
    phases_neg_x = (-shifted_x.flatten() / 255.0) * np.pi
    phases_neg_y = (-shifted_y.flatten() / 255.0) * np.pi

    probs_x = edge_detection_circuit(phases_base, phases_neg_x)
    probs_y = edge_detection_circuit(phases_base, phases_neg_y)

    # Reconstrucción Híbrida
    q_gx = extract_magnitude(probs_x, raw_img.shape)
    q_gy = extract_magnitude(probs_y, raw_img.shape)
    quantum_sobel = np.sqrt(q_gx**2 + q_gy**2)

    mae_score = mean_absolute_error(classic_sobel.flatten(), quantum_sobel.flatten())

    return q_gx + q_gy, classic_sobel, quantum_sobel, mae_score

# ==========================================
# 3. Preparación de Datasets
# ==========================================
print("Loading datasets...")

# Dataset 1: load_digits (Discreto, 8x8 nativo)
digits = load_digits()
images_discrete = [(img / 16.0) * 255.0 for img in digits.images[:5]]
targets = digits.target[:5]

# Dataset 2: OpenML MNIST (Continuo, interpolado a 8x8)
mnist_data = fetch_openml('mnist_784', version=1, cache=True, parser='auto')
X_cont = mnist_data.data.values.reshape(-1, 28, 28)
y_cont = mnist_data.target.values.astype(int)

images_continuous = []
for t in targets:
    idx = np.where(y_cont == t)[0][0]
    img_resized = resize(X_cont[idx], (8, 8), anti_aliasing=True, preserve_range=True)
    img_normalized = (img_resized / np.max(img_resized)) * 255.0
    images_continuous.append(img_normalized)

# ==========================================
# 4. Visualización Comparativa (Doble Subgráfica)
# ==========================================
fig = plt.figure(figsize=(27, 18))
# 9 columnas: 4 discreto | 1 separador | 4 continuo
gs = gridspec.GridSpec(5, 9, width_ratios=[1, 1, 1, 1, 0.2, 1, 1, 1, 1])

for idx in range(5):
    print(f"Processing digit {targets[idx]} ({idx+1}/5)...")

    raw_discrete = images_discrete[idx]
    raw_cont = images_continuous[idx]

    q_comps_disc, class_sobel_disc, q_sobel_disc, mae_disc = run_qpipe_sobel(raw_discrete)
    q_comps_cont, class_sobel_cont, q_sobel_cont, mae_cont = run_qpipe_sobel(raw_cont)

    # --- Bloque Izquierdo: MNIST Discreto ---
    ax0 = fig.add_subplot(gs[idx, 0])
    ax0.imshow(raw_discrete, cmap='gray', vmin=0, vmax=255)
    ax0.set_title(f"Original (Discrete): {targets[idx]}")
    ax0.axis('off')

    ax1 = fig.add_subplot(gs[idx, 1])
    ax1.imshow(np.clip(q_comps_disc, 0, 255), cmap='gray', vmin=0, vmax=255)
    ax1.set_title("Components ($|G_x| + |G_y|$)")
    ax1.axis('off')

    ax2 = fig.add_subplot(gs[idx, 2])
    ax2.imshow(np.clip(class_sobel_disc, 0, 255), cmap='gray', vmin=0, vmax=255)
    ax2.set_title("Classical Sobel ($L_2$)")
    ax2.axis('off')

    ax3 = fig.add_subplot(gs[idx, 3])
    ax3.imshow(np.clip(q_sobel_disc, 0, 255), cmap='gray', vmin=0, vmax=255)
    ax3.set_title(f"Q-PIPE Sobel ($L_2$) MAE: {mae_disc:.2f}")
    ax3.axis('off')

    # --- Bloque Derecho: MNIST Continuo (OpenML) ---
    ax5 = fig.add_subplot(gs[idx, 5])
    ax5.imshow(raw_cont, cmap='gray', vmin=0, vmax=255)
    ax5.set_title(f"Original (Continuous): {targets[idx]}")
    ax5.axis('off')

    ax6 = fig.add_subplot(gs[idx, 6])
    ax6.imshow(np.clip(q_comps_cont, 0, 255), cmap='gray', vmin=0, vmax=255)
    ax6.set_title("Components ($|G_x| + |G_y|$)")
    ax6.axis('off')

    ax7 = fig.add_subplot(gs[idx, 7])
    ax7.imshow(np.clip(class_sobel_cont, 0, 255), cmap='gray', vmin=0, vmax=255)
    ax7.set_title("Classical Sobel ($L_2$)")
    ax7.axis('off')

    ax8 = fig.add_subplot(gs[idx, 8])
    ax8.imshow(np.clip(q_sobel_cont, 0, 255), cmap='gray', vmin=0, vmax=255)
    ax8.set_title(f"Q-PIPE Sobel ($L_2$) MAE: {mae_cont:.2f}")
    ax8.axis('off')

plt.tight_layout()
plt.savefig("sobel_edge_detection_dual_subplot.png", dpi=600)
plt.savefig("sobel_edge_detection_dual_subplot.eps")
plt.show()
print("Quantum Sobel comparative processing finished.")

"""# Fotografia Natural Continua"""

def apply_dual_phases_with_gray_code(flat_phases_1, flat_phases_2, img_wires, est_wire, power):
    n = len(img_wires)
    total_states = 2**n
    gray_seq = [i ^ (i >> 1) for i in range(total_states)]

    for w in img_wires:
        qml.PauliX(wires=w)

    target_wire = img_wires[-1]
    control_wires = [est_wire] + list(img_wires[:-1])

    for step in range(total_states):
        curr_gray = gray_seq[step]
        pixel_idx = curr_gray

        if pixel_idx < len(flat_phases_1):
            phi1 = flat_phases_1[pixel_idx]
            phi2 = flat_phases_2[pixel_idx]

            if abs(phi1) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi1 * power, wires=target_wire)
            if abs(phi2) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi2 * power, wires=target_wire)

        if step < total_states - 1:
            next_gray = gray_seq[step + 1]
            diff = curr_gray ^ next_gray
            bit_changed_from_right = int(np.log2(diff))
            wire_to_flip = img_wires[n - 1 - bit_changed_from_right]
            qml.PauliX(wires=wire_to_flip)

    last_gray_bin = format(gray_seq[-1], f'0{n}b')
    for i, bit in enumerate(last_gray_bin):
        if bit == '0':
            qml.PauliX(wires=img_wires[i])

## Circuito cuantico y parametros
n_pixels = 64
n_image_wires = 6
n_estimation_wires = 8
total_wires = n_estimation_wires + n_image_wires

dev = qml.device('default.qubit', wires=total_wires)

@qml.qnode(dev)
def edge_detection_circuit(flat_p1, flat_p2):
    est_wires = list(range(n_estimation_wires))
    tgt_wires = list(range(n_estimation_wires, total_wires))

    for w in est_wires + tgt_wires:
        qml.Hadamard(wires=w)

    for i, est_wire in enumerate(reversed(est_wires)):
        power = 2**i
        apply_dual_phases_with_gray_code(flat_p1, flat_p2, tgt_wires, est_wire, power)

    qml.adjoint(qml.QFT)(wires=est_wires)
    return qml.probs(wires=est_wires + tgt_wires)

def extract_gradient_magnitude(probs, shape, threshold=0.001):
    weighted_mag_sum = np.zeros(shape, dtype=float)
    prob_sum = np.zeros(shape, dtype=float)

    for k, p in enumerate(probs):
        if p > threshold:
            bin_k = format(k, f'0{total_wires}b')
            est_int = int(bin_k[:n_estimation_wires], 2)
            pixel_idx = int(bin_k[n_estimation_wires:], 2)

            if pixel_idx < n_pixels:
                row, col = np.unravel_index(pixel_idx, shape)
                raw_val = (est_int / (2**n_estimation_wires)) * 255.0
                edge_magnitude = 2.0 * min(raw_val, 255.0 - raw_val)
                weighted_mag_sum[row, col] += p * edge_magnitude
                prob_sum[row, col] += p

    safe_prob_sum = np.where(prob_sum == 0, 1.0, prob_sum)
    return weighted_mag_sum / safe_prob_sum

# Cargar imagen de muestra y convertir a escala de grises.
china = load_sample_image("china.jpg")
gray_china = np.dot(china[...,:3], [0.2989, 0.5870, 0.1140])

# Extraer 4 parches de 8x8 de zonas con diferentes bordes arquitectónicos.
patches = [gray_china[150:158, 200:208], # Borde de techo
          gray_china[200:208, 300:308], # Textura de ladrillo
          gray_china[100:108, 150:158], # Contraste cielo/edificio
          gray_china[250:258, 400:408]]  # Borde difuso

fig, axes = plt.subplots(4, 4, figsize=(14, 13))

for idx, raw_img in enumerate(patches):
    shifted_x = np.roll(raw_img, shift=1, axis=1); shifted_x[:, 0] = 0
    shifted_y = np.roll(raw_img, shift=1, axis=0); shifted_y[0, :] = 0

    phases_base = (raw_img.flatten() / 255.0) * np.pi
    phases_neg_x = (-shifted_x.flatten() / 255.0) * np.pi
    phases_neg_y = (-shifted_y.flatten() / 255.0) * np.pi

    print(f"Ejecutando Q-PIPE Sobel para el Parche {idx+1}/4...")
    probs_x = edge_detection_circuit(phases_base, phases_neg_x)
    probs_y = edge_detection_circuit(phases_base, phases_neg_y)

    q_gx = extract_gradient_magnitude(probs_x, raw_img.shape)
    q_gy = extract_gradient_magnitude(probs_y, raw_img.shape)
    quantum_sobel = np.sqrt(q_gx**2 + q_gy**2)

    c_gx = np.abs(raw_img - shifted_x)
    c_gy = np.abs(raw_img - shifted_y)
    classic_sobel = np.sqrt(c_gx**2 + c_gy**2)

    mae_score = mean_absolute_error(classic_sobel.flatten(), quantum_sobel.flatten())
    print(f"  -> MAE Sobel (Fotografía): {mae_score:.4f}")

    axes[idx, 0].imshow(raw_img, cmap='gray', vmin=0, vmax=255)
    axes[idx, 0].set_title(f"Parche Original {idx+1}")
    axes[idx, 0].axis('off')

    axes[idx, 1].imshow(np.clip(q_gx + q_gy, 0, 255), cmap='gray', vmin=0, vmax=255)
    axes[idx, 1].set_title("Componentes QED\n($|G_x| + |G_y|$)")
    axes[idx, 1].axis('off')

    axes[idx, 2].imshow(np.clip(classic_sobel, 0, 255), cmap='gray', vmin=0, vmax=255)
    axes[idx, 2].set_title("Sobel Clásico\n$\sqrt{G_x^2 + G_y^2}$")
    axes[idx, 2].axis('off')

    axes[idx, 3].imshow(np.clip(quantum_sobel, 0, 255), cmap='gray', vmin=0, vmax=255)
    axes[idx, 3].set_title(f"Sobel Q-PIPE\nMAE: {mae_score:.2f}")
    axes[idx, 3].axis('off')

plt.tight_layout()
plt.savefig("qpipe_sobel_natural_image.png", dpi=600)
plt.show()
print("Procesamiento de imagen natural finalizado.")

"""# Multiples datasets (MNIST, Olivetti faces, Fashin MNIST y dataset médico sintetico-ruido speckle)

### Ejemplos de imagenes de cada dataset
"""

# MNIST (8x8 de origen)
mnist_raw = load_digits().images[0]
img_mnist = (mnist_raw / 16.0) * 255.0

# Olivetti Faces (de 64x64 a 8x8)
face_raw = fetch_olivetti_faces().images[10]
img_face = resize(face_raw, (8, 8), anti_aliasing=True) * 255.0

# Fashion-MNIST (de 28x28 a 8x8) ---
fmnist_data = fetch_openml('Fashion-MNIST', version=1, cache=True, parser='auto').data.values
img_fmnist_raw = fmnist_data[0].reshape(28, 28)
img_fmnist = resize(img_fmnist_raw, (8, 8), anti_aliasing=True, preserve_range=True)

# Medical synth (ruido Speckle/difusion con 8x8) ---
img_med_base = np.zeros((8, 8))
img_med_base[3:6, 3:6] = 150.0
noise = np.random.normal(1, 0.2, (8, 8))
img_medical = np.clip(img_med_base * noise, 0, 255)

datasets = [("MNIST\n(Discreet contours)", img_mnist),
            ("Olivetti Faces\n(Continous gradient)", img_face),
            ("Fashion-MNIST\n(Low Contrast Textures)", img_fmnist),
            ("Synth. Med\n(Speckle/Diffuse Noise)", img_medical)]

fig, axes = plt.subplots(1, 4, figsize=(16, 5))

for ax, (title, img) in zip(axes, datasets):
    ax.imshow(img, cmap='gray', vmin=0, vmax=255)
    ax.set_title(title, fontsize=12, pad=10)
    ax.axis('off')

    # Anotar los valores numéricos de TODA la matriz (8x8)
    for i in range(8):
        for j in range(8):
            val = int(img[i, j])
            color = 'white' if val < 128 else 'black'
            ax.text(j, i, str(val), ha='center', va='center', color=color, fontsize=7)

plt.tight_layout()
plt.savefig("qpipe_dataset_samples_full.png", dpi=600, bbox_inches='tight')
plt.savefig("qpipe_dataset_samples_full.eps", bbox_inches='tight')
plt.show()

"""### MAE (Sobel) para los 4 datasets con 100 muestras"""

### Q-PIPE (circuito cuantico) ###
def apply_dual_phases_with_gray_code(flat_phases_1, flat_phases_2, img_wires, est_wire, power):
    n = len(img_wires)
    total_states = 2**n
    gray_seq = [i ^ (i >> 1) for i in range(total_states)]

    for w in img_wires:
        qml.PauliX(wires=w)

    target_wire = img_wires[-1]
    control_wires = [est_wire] + list(img_wires[:-1])

    for step in range(total_states):
        curr_gray = gray_seq[step]
        pixel_idx = curr_gray

        if pixel_idx < len(flat_phases_1):
            phi1 = flat_phases_1[pixel_idx]
            phi2 = flat_phases_2[pixel_idx]

            if abs(phi1) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi1 * power, wires=target_wire)
            if abs(phi2) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi2 * power, wires=target_wire)

        if step < total_states - 1:
            next_gray = gray_seq[step + 1]
            diff = curr_gray ^ next_gray
            bit_changed_from_right = int(np.log2(diff))
            wire_to_flip = img_wires[n - 1 - bit_changed_from_right]
            qml.PauliX(wires=wire_to_flip)

    last_gray_bin = format(gray_seq[-1], f'0{n}b')
    for i, bit in enumerate(last_gray_bin):
        if bit == '0':
            qml.PauliX(wires=img_wires[i])

## Q-PIPE (main ejecucion)
def run_qpipe_sobel(raw_img, n_estimation_wires):
    n_pixels = 64
    n_image_wires = 6
    total_wires = n_estimation_wires + n_image_wires

    dev = qml.device('default.qubit', wires=total_wires)

    @qml.qnode(dev)
    def edge_circuit(flat_p1, flat_p2):
        est_wires = list(range(n_estimation_wires))
        tgt_wires = list(range(n_estimation_wires, total_wires))
        for w in est_wires + tgt_wires:
            qml.Hadamard(wires=w)
        for i, est_wire in enumerate(reversed(est_wires)):
            power = 2**i
            apply_dual_phases_with_gray_code(flat_p1, flat_p2, tgt_wires, est_wire, power)
        qml.adjoint(qml.QFT)(wires=est_wires)
        return qml.probs(wires=est_wires + tgt_wires)

    # Escalamiento de media fase
    shifted_x = np.roll(raw_img, shift=1, axis=1); shifted_x[:, 0] = 0
    shifted_y = np.roll(raw_img, shift=1, axis=0); shifted_y[0, :] = 0

    phases_base = (raw_img.flatten() / 255.0) * np.pi
    phases_neg_x = (-shifted_x.flatten() / 255.0) * np.pi
    phases_neg_y = (-shifted_y.flatten() / 255.0) * np.pi

    def extract_magnitude(probs):
        weighted_mag_sum = np.zeros(raw_img.shape, dtype=float)
        prob_sum = np.zeros(raw_img.shape, dtype=float)
        threshold = 0.0005

        for k, p in enumerate(probs):
            if p > threshold:
                bin_k = format(k, f'0{total_wires}b')
                est_int = int(bin_k[:n_estimation_wires], 2)
                pixel_idx = int(bin_k[n_estimation_wires:], 2)
                if pixel_idx < n_pixels:
                    row, col = np.unravel_index(pixel_idx, raw_img.shape)
                    raw_val = (est_int / (2**n_estimation_wires)) * 255.0
                    edge_magnitude = 2.0 * min(raw_val, 255.0 - raw_val)
                    weighted_mag_sum[row, col] += p * edge_magnitude
                    prob_sum[row, col] += p

        safe_prob_sum = np.where(prob_sum == 0, 1.0, prob_sum)
        return weighted_mag_sum / safe_prob_sum

    probs_x = edge_circuit(phases_base, phases_neg_x)
    probs_y = edge_circuit(phases_base, phases_neg_y)

    q_gx = extract_magnitude(probs_x)
    q_gy = extract_magnitude(probs_y)
    quantum_sobel = np.sqrt(q_gx**2 + q_gy**2)

    c_gx = np.abs(raw_img - shifted_x)
    c_gy = np.abs(raw_img - shifted_y)
    classic_sobel = np.sqrt(c_gx**2 + c_gy**2)

    return mean_absolute_error(classic_sobel.flatten(), quantum_sobel.flatten())

#
def get_datasets(n_instances=100):
    datasets = {}
    print("Cargando y procesando datasets...")

    # 1. MNIST
    digits = load_digits()
    datasets['MNIST (8x8)'] = [(img / 16.0) * 255.0 for img in digits.images[:n_instances]]

    # 2. Olivetti Faces
    faces = fetch_olivetti_faces().images
    datasets['Olivetti (64x64 to 8x8)'] = [resize(img, (8, 8), anti_aliasing=True) * 255.0 for img in faces[:n_instances]]

    # 3. Fashion-MNIST (CORREGIDO: preserve_range=True)
    f_mnist = fetch_openml('Fashion-MNIST', version=1, cache=True, parser='auto').data.values
    f_mnist_images = f_mnist.reshape(-1, 28, 28)[:n_instances]
    datasets['Fashion-MNIST (28x28 to 8x8)'] = [resize(img, (8, 8), anti_aliasing=True, preserve_range=True) for img in f_mnist_images]

    # 4. Dataset Médico Sintético
    med_images = []
    for _ in range(n_instances):
        base = np.zeros((8, 8))
        cx, cy = np.random.randint(2, 6, size=2)
        base[cx-1:cx+2, cy-1:cy+2] = 150.0
        noise = np.random.normal(1, 0.2, (8, 8))
        img_med = np.clip(base * noise, 0, 255)
        med_images.append(img_med)
    datasets['Medical Synth (8x8)'] = med_images

    return datasets

# ==========================================
# 4. Ejecución y Generación de Gráficos
# ==========================================
n_instances = 100 # Puedes reducir este número para pruebas rápidas
datasets = get_datasets(n_instances)
qubit_levels = [8, 9, 10]

for q_level in qubit_levels:
    print(f"\n--- Iniciando evaluación para {q_level} Qubits de Estimación ---")
    results = {}

    for name, images in datasets.items():
        mae_list = []
        print(f"Procesando {name}...")
        for i, img in enumerate(images):
            mae = run_qpipe_sobel(img, q_level)
            mae_list.append(mae)
            if (i+1) % 25 == 0:
                print(f"  [{i+1}/{n_instances}] completados.")
        results[name] = mae_list

    plt.figure(figsize=(10, 6))
    plt.boxplot(results.values(), labels=results.keys(), patch_artist=True,
                boxprops=dict(facecolor='lightblue', color='blue'),
                medianprops=dict(color='red', linewidth=2))

    plt.title(f'MAE Q-PIPE vs Classic\n({q_level} Estimation qubits | 100 Instances/Dataset)', fontsize=14)
    plt.ylabel('Mean Absolute Error (Intensity 0-255)', fontsize=12)
    plt.grid(axis='y', linestyle='--', alpha=0.7)

    filename = f"qpipe_benchmark_{q_level}qubits.png"
    filename2 = f"qpipe_benchmark_{q_level}qubits.eps"
    plt.tight_layout()
    plt.savefig(filename, dpi=600)
    plt.savefig(filename2)
    plt.show()
    print(f"Gráfica guardada como {filename}")

"""### Variacion de resolucion (8x8, 12x12, 18x18, 20x20 y 24x24) en imagen"""

### Q-PIPE (circuito cuantico) ##
def apply_dual_phases_with_gray_code(flat_phases_1, flat_phases_2, img_wires, est_wire, power):
    n = len(img_wires)
    total_states = 2**n
    gray_seq = [i ^ (i >> 1) for i in range(total_states)]

    for w in img_wires:
        qml.PauliX(wires=w)

    target_wire = img_wires[-1]
    control_wires = [est_wire] + list(img_wires[:-1])

    for step in range(total_states):
        curr_gray = gray_seq[step]
        pixel_idx = curr_gray

        if pixel_idx < len(flat_phases_1):
            phi1 = flat_phases_1[pixel_idx]
            phi2 = flat_phases_2[pixel_idx]

            if abs(phi1) > 1e-5: # Umbral minimo de consideracion.
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi1 * power, wires=target_wire)
            if abs(phi2) > 1e-5:
                qml.ctrl(qml.PhaseShift, control=control_wires)(phi2 * power, wires=target_wire)

        if step < total_states - 1:
            next_gray = gray_seq[step + 1]
            diff = curr_gray ^ next_gray
            bit_changed_from_right = int(np.log2(diff))
            wire_to_flip = img_wires[n - 1 - bit_changed_from_right]
            qml.PauliX(wires=wire_to_flip)

    last_gray_bin = format(gray_seq[-1], f'0{n}b')
    for i, bit in enumerate(last_gray_bin):
        if bit == '0':
            qml.PauliX(wires=img_wires[i])

## Q-PIPE (main ejecución)
def run_qpipe_dynamic_resolution(raw_img, n_estimation_wires=8):
    h, w = raw_img.shape
    n_pixels = h * w
    n_image_wires = int(np.ceil(np.log2(n_pixels)))
    total_wires = n_estimation_wires + n_image_wires

    dev = qml.device('default.qubit', wires=total_wires)

    @qml.qnode(dev)
    def edge_circuit(flat_p1, flat_p2):
        est_wires = list(range(n_estimation_wires))
        tgt_wires = list(range(n_estimation_wires, total_wires))

        for wire in est_wires + tgt_wires:
            qml.Hadamard(wires=wire)

        for i, est_wire in enumerate(reversed(est_wires)):
            power = 2**i
            apply_dual_phases_with_gray_code(flat_p1, flat_p2, tgt_wires, est_wire, power)

        qml.adjoint(qml.QFT)(wires=est_wires)
        return qml.probs(wires=est_wires + tgt_wires)

    # Preprocesamiento clasico
    shifted_x = np.roll(raw_img, shift=1, axis=1); shifted_x[:, 0] = 0
    shifted_y = np.roll(raw_img, shift=1, axis=0); shifted_y[0, :] = 0

    phases_base = (raw_img.flatten() / 255.0) * np.pi
    phases_neg_x = (-shifted_x.flatten() / 255.0) * np.pi
    phases_neg_y = (-shifted_y.flatten() / 255.0) * np.pi

    def extract_magnitude(probs):
        weighted_mag_sum = np.zeros(raw_img.shape, dtype=float)
        prob_sum = np.zeros(raw_img.shape, dtype=float)
        threshold = 0.00005 # Probability threshold estatico, se puede aplicar ecuacion para mejorar.
        # threshold = 0.0019

        for k, p in enumerate(probs):
            if p > threshold:
                bin_k = format(k, f'0{total_wires}b')
                est_int = int(bin_k[:n_estimation_wires], 2)
                pixel_idx = int(bin_k[n_estimation_wires:], 2)

                if pixel_idx < n_pixels:
                    row, col = np.unravel_index(pixel_idx, raw_img.shape)
                    raw_val = (est_int / (2**n_estimation_wires)) * 255.0
                    edge_magnitude = 2.0 * min(raw_val, 255.0 - raw_val)
                    weighted_mag_sum[row, col] += p * edge_magnitude
                    prob_sum[row, col] += p

        safe_prob_sum = np.where(prob_sum == 0, 1.0, prob_sum)
        return weighted_mag_sum / safe_prob_sum

    probs_x = edge_circuit(phases_base, phases_neg_x)
    probs_y = edge_circuit(phases_base, phases_neg_y)

    q_gx = extract_magnitude(probs_x)
    q_gy = extract_magnitude(probs_y)
    quantum_sobel = np.sqrt(q_gx**2 + q_gy**2)

    c_gx = np.abs(raw_img - shifted_x)
    c_gy = np.abs(raw_img - shifted_y)
    classic_sobel = np.sqrt(c_gx**2 + c_gy**2)

    return mean_absolute_error(classic_sobel.flatten(), quantum_sobel.flatten())

## MAIN ##
n_instances = 10  # Solo diez muestras por resolucion 24x24 que es altamente costosa de simular.
resolutions = [8, 12, 16, 20, 24]
faces_raw = fetch_olivetti_faces().images[:n_instances]

means = []
stds = []

print("Iniciando análisis de escalabilidad espacial...")
for res in resolutions:
    print(f"\nProcesando resolución {res}x{res}...")
    mae_list = []

    for i, img in enumerate(faces_raw):
        # Redimensionar la imagen a la resolucion objetivo
        img_resized = resize(img, (res, res), anti_aliasing=True) * 255.0
        mae = run_qpipe_dynamic_resolution(img_resized, n_estimation_wires=8)
        mae_list.append(mae)
        print(f"  Instancia {i+1}/{n_instances} -> MAE: {mae:.2f}")

    means.append(np.mean(mae_list))
    stds.append(np.std(mae_list))

means = np.array(means)
stds = np.array(stds)

## Visualización.
plt.figure(figsize=(9, 6))

# Linea principal con los promedios.
plt.plot(resolutions, means, marker='o', color='darkblue', linewidth=2, label='Promedio MAE')

# Banda sombreada para la desviación estandar.
plt.fill_between(resolutions, means - stds, means + stds, color='blue', alpha=0.2, label='Desviación Estándar ($\pm 1\sigma$)')

plt.title('Impacto de la Resolución Espacial en la Precisión de Q-PIPE\n(Dataset: Olivetti Faces | 8 Qubits Estimación)', fontsize=14)
plt.xlabel('Resolución de la Imagen ($N \\times N$ píxeles)', fontsize=12)
plt.ylabel('Mean Absolute Error (Niveles 0-255)', fontsize=12)
plt.xticks(resolutions, [f'{r}x{r}' for r in resolutions])
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(loc='upper right')

plt.tight_layout()
plt.savefig("qpipe_resolution_scaling_diff_prob_threshold.png", dpi=600)
plt.savefig("qpipe_resolution_scaling_diff_prob_threshold.eps")
plt.show()
print("Gráfico de escalabilidad generado con éxito.")

"""#"""
